# yaml-language-server: $schema=https://raw.githubusercontent.com/release-drafter/release-drafter/34d80673e067bdc0c24568d3af899c216adcfaa9/schema.json
categories:
  - type: "pre-exclude"
    when:
      label: "skip-changelog"
  - title: ":boom: Breaking Changes"
    when:
      label: "breaking"
  - title: ":rocket: Features"
    when:
      label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    when:
      label: "removal"
  - title: ":beetle: Fixes"
    when:
      label: "bug"
  - title: ":racehorse: Performance"
    when:
      label: "performance"
  - title: ":rotating_light: Testing"
    when:
      label: "testing"
  - title: ":construction_worker: Continuous Integration"
    when:
      label: "ci"
  - title: ":books: Documentation"
    when:
      label: "documentation"
  - title: ":hammer: Refactoring"
    when:
      label: "refactoring"
  - title: ":lipstick: Style"
    when:
      label: "style"
  - title: ":package: Dependencies"
    when:
      labels:
        - "dependencies"
autolabeler:
  - label: "documentation"
    files:
      - "**/*.md"
      - "docs/**"
      - "backstage.yaml"
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "enhancement"
    branch:
      - '/feat\/.+/'
  - label: "refactoring"
    branch:
      - '/refactor\/.+/'
    title:
      - "/^refactor/i"
  - label: "testing"
    branch:
      - '/test\/.+/'
  - label: "skip-changelog"
    branch:
      - '/release\/.+/'
      - '/chore\/.+/'
  - label: "breaking"
    title:
      - "/breaking change/i"
  - label: "ci"
    files:
      - ".github/*"
      - "noxfile.py"
    branch:
      - '/ci\/.+/'
template: |
  ## Changes

  $CHANGES
