/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangelogResource
 */
export interface ChangelogResource {
    /**
     * 
     * @type {Date}
     * @memberof ChangelogResource
     */
    changeOccured?: Date;
    /**
     * 
     * @type {string}
     * @memberof ChangelogResource
     */
    description?: string;
}

/**
 * Check if a given object implements the ChangelogResource interface.
 */
export function instanceOfChangelogResource(value: object): value is ChangelogResource {
    return true;
}

export function ChangelogResourceFromJSON(json: any): ChangelogResource {
    return ChangelogResourceFromJSONTyped(json, false);
}

export function ChangelogResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangelogResource {
    if (json == null) {
        return json;
    }
    return {
        
        'changeOccured': json['changeOccured'] == null ? undefined : (new Date(json['changeOccured'])),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ChangelogResourceToJSON(json: any): ChangelogResource {
    return ChangelogResourceToJSONTyped(json, false);
}

export function ChangelogResourceToJSONTyped(value?: ChangelogResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changeOccured': value['changeOccured'] == null ? value['changeOccured'] : value['changeOccured'].toISOString(),
        'description': value['description'],
    };
}

