/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ClassificationFamilySummaryResource
 */
export interface ClassificationFamilySummaryResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationFamilySummaryResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationFamilySummaryResource
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ClassificationFamilySummaryResource
     */
    numberOfClassifications?: number;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof ClassificationFamilySummaryResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof ClassificationFamilySummaryResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof ClassificationFamilySummaryResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the ClassificationFamilySummaryResource interface.
 */
export function instanceOfClassificationFamilySummaryResource(value: object): value is ClassificationFamilySummaryResource {
    return true;
}

export function ClassificationFamilySummaryResourceFromJSON(json: any): ClassificationFamilySummaryResource {
    return ClassificationFamilySummaryResourceFromJSONTyped(json, false);
}

export function ClassificationFamilySummaryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationFamilySummaryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'numberOfClassifications': json['numberOfClassifications'] == null ? undefined : json['numberOfClassifications'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function ClassificationFamilySummaryResourceToJSON(json: any): ClassificationFamilySummaryResource {
    return ClassificationFamilySummaryResourceToJSONTyped(json, false);
}

export function ClassificationFamilySummaryResourceToJSONTyped(value?: ClassificationFamilySummaryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'numberOfClassifications': value['numberOfClassifications'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

