/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ClassificationVersionSummaryResource
 */
export interface ClassificationVersionSummaryResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationVersionSummaryResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationVersionSummaryResource
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationVersionSummaryResource
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationVersionSummaryResource
     */
    validTo?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationVersionSummaryResource
     */
    lastModified?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationVersionSummaryResource
     */
    published?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof ClassificationVersionSummaryResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof ClassificationVersionSummaryResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof ClassificationVersionSummaryResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the ClassificationVersionSummaryResource interface.
 */
export function instanceOfClassificationVersionSummaryResource(value: object): value is ClassificationVersionSummaryResource {
    return true;
}

export function ClassificationVersionSummaryResourceFromJSON(json: any): ClassificationVersionSummaryResource {
    return ClassificationVersionSummaryResourceFromJSONTyped(json, false);
}

export function ClassificationVersionSummaryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationVersionSummaryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'validFrom': json['validFrom'] == null ? undefined : (new Date(json['validFrom'])),
        'validTo': json['validTo'] == null ? undefined : (new Date(json['validTo'])),
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'published': json['published'] == null ? undefined : json['published'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function ClassificationVersionSummaryResourceToJSON(json: any): ClassificationVersionSummaryResource {
    return ClassificationVersionSummaryResourceToJSONTyped(json, false);
}

export function ClassificationVersionSummaryResourceToJSONTyped(value?: ClassificationVersionSummaryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'validFrom': value['validFrom'] == null ? value['validFrom'] : value['validFrom'].toISOString().substring(0,10),
        'validTo': value['validTo'] == null ? value['validTo'] : value['validTo'].toISOString().substring(0,10),
        'lastModified': value['lastModified'] == null ? value['lastModified'] : value['lastModified'].toISOString(),
        'published': value['published'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

