/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ContactPersonResource } from './ContactPersonResource';
import {
    ContactPersonResourceFromJSON,
    ContactPersonResourceFromJSONTyped,
    ContactPersonResourceToJSON,
    ContactPersonResourceToJSONTyped,
} from './ContactPersonResource';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { ClassificationVersionSummaryResource } from './ClassificationVersionSummaryResource';
import {
    ClassificationVersionSummaryResourceFromJSON,
    ClassificationVersionSummaryResourceFromJSONTyped,
    ClassificationVersionSummaryResourceToJSON,
    ClassificationVersionSummaryResourceToJSONTyped,
} from './ClassificationVersionSummaryResource';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ClassificationResource
 */
export interface ClassificationResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationResource
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassificationResource
     */
    classificationType?: string;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationResource
     */
    lastModified?: Date;
    /**
     * 
     * @type {string}
     * @memberof ClassificationResource
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationResource
     */
    primaryLanguage?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClassificationResource
     */
    copyrighted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClassificationResource
     */
    includeShortName?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClassificationResource
     */
    includeNotes?: boolean;
    /**
     * 
     * @type {ContactPersonResource}
     * @memberof ClassificationResource
     */
    contactPerson?: ContactPersonResource;
    /**
     * 
     * @type {string}
     * @memberof ClassificationResource
     */
    owningSection?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationResource
     */
    statisticalUnits?: Array<string>;
    /**
     * 
     * @type {Array<ClassificationVersionSummaryResource>}
     * @memberof ClassificationResource
     */
    versions?: Array<ClassificationVersionSummaryResource>;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof ClassificationResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {number}
     * @memberof ClassificationResource
     */
    classificationFamilyId?: number;
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof ClassificationResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof ClassificationResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the ClassificationResource interface.
 */
export function instanceOfClassificationResource(value: object): value is ClassificationResource {
    return true;
}

export function ClassificationResourceFromJSON(json: any): ClassificationResource {
    return ClassificationResourceFromJSONTyped(json, false);
}

export function ClassificationResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'classificationType': json['classificationType'] == null ? undefined : json['classificationType'],
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'description': json['description'] == null ? undefined : json['description'],
        'primaryLanguage': json['primaryLanguage'] == null ? undefined : json['primaryLanguage'],
        'copyrighted': json['copyrighted'] == null ? undefined : json['copyrighted'],
        'includeShortName': json['includeShortName'] == null ? undefined : json['includeShortName'],
        'includeNotes': json['includeNotes'] == null ? undefined : json['includeNotes'],
        'contactPerson': json['contactPerson'] == null ? undefined : ContactPersonResourceFromJSON(json['contactPerson']),
        'owningSection': json['owningSection'] == null ? undefined : json['owningSection'],
        'statisticalUnits': json['statisticalUnits'] == null ? undefined : json['statisticalUnits'],
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(ClassificationVersionSummaryResourceFromJSON)),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'classificationFamilyId': json['classificationFamilyId'] == null ? undefined : json['classificationFamilyId'],
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function ClassificationResourceToJSON(json: any): ClassificationResource {
    return ClassificationResourceToJSONTyped(json, false);
}

export function ClassificationResourceToJSONTyped(value?: ClassificationResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'classificationType': value['classificationType'],
        'lastModified': value['lastModified'] == null ? value['lastModified'] : value['lastModified'].toISOString(),
        'description': value['description'],
        'primaryLanguage': value['primaryLanguage'],
        'copyrighted': value['copyrighted'],
        'includeShortName': value['includeShortName'],
        'includeNotes': value['includeNotes'],
        'contactPerson': ContactPersonResourceToJSON(value['contactPerson']),
        'owningSection': value['owningSection'],
        'statisticalUnits': value['statisticalUnits'],
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(ClassificationVersionSummaryResourceToJSON)),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'classificationFamilyId': value['classificationFamilyId'],
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

