/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepresentationModelObject } from './RepresentationModelObject';
import {
    RepresentationModelObjectFromJSON,
    RepresentationModelObjectFromJSONTyped,
    RepresentationModelObjectToJSON,
    RepresentationModelObjectToJSONTyped,
} from './RepresentationModelObject';

/**
 * 
 * @export
 * @interface ClassificationVariantSummaryResourceEmbedded
 */
export interface ClassificationVariantSummaryResourceEmbedded {
    /**
     * 
     * @type {Array<RepresentationModelObject>}
     * @memberof ClassificationVariantSummaryResourceEmbedded
     */
    representationModelList?: Array<RepresentationModelObject>;
}

/**
 * Check if a given object implements the ClassificationVariantSummaryResourceEmbedded interface.
 */
export function instanceOfClassificationVariantSummaryResourceEmbedded(value: object): value is ClassificationVariantSummaryResourceEmbedded {
    return true;
}

export function ClassificationVariantSummaryResourceEmbeddedFromJSON(json: any): ClassificationVariantSummaryResourceEmbedded {
    return ClassificationVariantSummaryResourceEmbeddedFromJSONTyped(json, false);
}

export function ClassificationVariantSummaryResourceEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationVariantSummaryResourceEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'representationModelList': json['representationModelList'] == null ? undefined : ((json['representationModelList'] as Array<any>).map(RepresentationModelObjectFromJSON)),
    };
}

export function ClassificationVariantSummaryResourceEmbeddedToJSON(json: any): ClassificationVariantSummaryResourceEmbedded {
    return ClassificationVariantSummaryResourceEmbeddedToJSONTyped(json, false);
}

export function ClassificationVariantSummaryResourceEmbeddedToJSONTyped(value?: ClassificationVariantSummaryResourceEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'representationModelList': value['representationModelList'] == null ? undefined : ((value['representationModelList'] as Array<any>).map(RepresentationModelObjectToJSON)),
    };
}

