/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationItemResource
 */
export interface ClassificationItemResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationItemResource
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationItemResource
     */
    parentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationItemResource
     */
    level?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationItemResource
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationItemResource
     */
    shortName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationItemResource
     */
    notes?: string;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationItemResource
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationItemResource
     */
    validTo?: Date;
}

/**
 * Check if a given object implements the ClassificationItemResource interface.
 */
export function instanceOfClassificationItemResource(value: object): value is ClassificationItemResource {
    return true;
}

export function ClassificationItemResourceFromJSON(json: any): ClassificationItemResource {
    return ClassificationItemResourceFromJSONTyped(json, false);
}

export function ClassificationItemResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationItemResource {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'parentCode': json['parentCode'] == null ? undefined : json['parentCode'],
        'level': json['level'] == null ? undefined : json['level'],
        'name': json['name'] == null ? undefined : json['name'],
        'shortName': json['shortName'] == null ? undefined : json['shortName'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'validFrom': json['validFrom'] == null ? undefined : (new Date(json['validFrom'])),
        'validTo': json['validTo'] == null ? undefined : (new Date(json['validTo'])),
    };
}

export function ClassificationItemResourceToJSON(json: any): ClassificationItemResource {
    return ClassificationItemResourceToJSONTyped(json, false);
}

export function ClassificationItemResourceToJSONTyped(value?: ClassificationItemResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'parentCode': value['parentCode'],
        'level': value['level'],
        'name': value['name'],
        'shortName': value['shortName'],
        'notes': value['notes'],
        'validFrom': value['validFrom'] == null ? value['validFrom'] : value['validFrom'].toISOString().substring(0,10),
        'validTo': value['validTo'] == null ? value['validTo'] : value['validTo'].toISOString().substring(0,10),
    };
}

