/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClassificationVariantSummaryResource } from './ClassificationVariantSummaryResource';
import {
    ClassificationVariantSummaryResourceFromJSON,
    ClassificationVariantSummaryResourceFromJSONTyped,
    ClassificationVariantSummaryResourceToJSON,
    ClassificationVariantSummaryResourceToJSONTyped,
} from './ClassificationVariantSummaryResource';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ChangelogResource } from './ChangelogResource';
import {
    ChangelogResourceFromJSON,
    ChangelogResourceFromJSONTyped,
    ChangelogResourceToJSON,
    ChangelogResourceToJSONTyped,
} from './ChangelogResource';
import type { ContactPersonResource } from './ContactPersonResource';
import {
    ContactPersonResourceFromJSON,
    ContactPersonResourceFromJSONTyped,
    ContactPersonResourceToJSON,
    ContactPersonResourceToJSONTyped,
} from './ContactPersonResource';
import type { LevelResource } from './LevelResource';
import {
    LevelResourceFromJSON,
    LevelResourceFromJSONTyped,
    LevelResourceToJSON,
    LevelResourceToJSONTyped,
} from './LevelResource';
import type { ClassificationItemResource } from './ClassificationItemResource';
import {
    ClassificationItemResourceFromJSON,
    ClassificationItemResourceFromJSONTyped,
    ClassificationItemResourceToJSON,
    ClassificationItemResourceToJSONTyped,
} from './ClassificationItemResource';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { CorrespondenceTableSummaryResource } from './CorrespondenceTableSummaryResource';
import {
    CorrespondenceTableSummaryResourceFromJSON,
    CorrespondenceTableSummaryResourceFromJSONTyped,
    CorrespondenceTableSummaryResourceToJSON,
    CorrespondenceTableSummaryResourceToJSONTyped,
} from './CorrespondenceTableSummaryResource';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ClassificationVersionResource
 */
export interface ClassificationVersionResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationVersionResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationVersionResource
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationVersionResource
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationVersionResource
     */
    validTo?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationVersionResource
     */
    lastModified?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationVersionResource
     */
    published?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ClassificationVersionResource
     */
    introduction?: string;
    /**
     * 
     * @type {ContactPersonResource}
     * @memberof ClassificationVersionResource
     */
    contactPerson?: ContactPersonResource;
    /**
     * 
     * @type {string}
     * @memberof ClassificationVersionResource
     */
    owningSection?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationVersionResource
     */
    legalBase?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationVersionResource
     */
    publications?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationVersionResource
     */
    derivedFrom?: string;
    /**
     * 
     * @type {Array<CorrespondenceTableSummaryResource>}
     * @memberof ClassificationVersionResource
     */
    correspondenceTables?: Array<CorrespondenceTableSummaryResource>;
    /**
     * 
     * @type {Array<ClassificationVariantSummaryResource>}
     * @memberof ClassificationVersionResource
     */
    classificationVariants?: Array<ClassificationVariantSummaryResource>;
    /**
     * 
     * @type {Array<ChangelogResource>}
     * @memberof ClassificationVersionResource
     */
    changelogs?: Array<ChangelogResource>;
    /**
     * 
     * @type {Array<LevelResource>}
     * @memberof ClassificationVersionResource
     */
    levels?: Array<LevelResource>;
    /**
     * 
     * @type {Array<ClassificationItemResource>}
     * @memberof ClassificationVersionResource
     */
    classificationItems?: Array<ClassificationItemResource>;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof ClassificationVersionResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof ClassificationVersionResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof ClassificationVersionResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the ClassificationVersionResource interface.
 */
export function instanceOfClassificationVersionResource(value: object): value is ClassificationVersionResource {
    return true;
}

export function ClassificationVersionResourceFromJSON(json: any): ClassificationVersionResource {
    return ClassificationVersionResourceFromJSONTyped(json, false);
}

export function ClassificationVersionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationVersionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'validFrom': json['validFrom'] == null ? undefined : (new Date(json['validFrom'])),
        'validTo': json['validTo'] == null ? undefined : (new Date(json['validTo'])),
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'published': json['published'] == null ? undefined : json['published'],
        'introduction': json['introduction'] == null ? undefined : json['introduction'],
        'contactPerson': json['contactPerson'] == null ? undefined : ContactPersonResourceFromJSON(json['contactPerson']),
        'owningSection': json['owningSection'] == null ? undefined : json['owningSection'],
        'legalBase': json['legalBase'] == null ? undefined : json['legalBase'],
        'publications': json['publications'] == null ? undefined : json['publications'],
        'derivedFrom': json['derivedFrom'] == null ? undefined : json['derivedFrom'],
        'correspondenceTables': json['correspondenceTables'] == null ? undefined : ((json['correspondenceTables'] as Array<any>).map(CorrespondenceTableSummaryResourceFromJSON)),
        'classificationVariants': json['classificationVariants'] == null ? undefined : ((json['classificationVariants'] as Array<any>).map(ClassificationVariantSummaryResourceFromJSON)),
        'changelogs': json['changelogs'] == null ? undefined : ((json['changelogs'] as Array<any>).map(ChangelogResourceFromJSON)),
        'levels': json['levels'] == null ? undefined : ((json['levels'] as Array<any>).map(LevelResourceFromJSON)),
        'classificationItems': json['classificationItems'] == null ? undefined : ((json['classificationItems'] as Array<any>).map(ClassificationItemResourceFromJSON)),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function ClassificationVersionResourceToJSON(json: any): ClassificationVersionResource {
    return ClassificationVersionResourceToJSONTyped(json, false);
}

export function ClassificationVersionResourceToJSONTyped(value?: ClassificationVersionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'validFrom': value['validFrom'] == null ? value['validFrom'] : value['validFrom'].toISOString().substring(0,10),
        'validTo': value['validTo'] == null ? value['validTo'] : value['validTo'].toISOString().substring(0,10),
        'lastModified': value['lastModified'] == null ? value['lastModified'] : value['lastModified'].toISOString(),
        'published': value['published'],
        'introduction': value['introduction'],
        'contactPerson': ContactPersonResourceToJSON(value['contactPerson']),
        'owningSection': value['owningSection'],
        'legalBase': value['legalBase'],
        'publications': value['publications'],
        'derivedFrom': value['derivedFrom'],
        'correspondenceTables': value['correspondenceTables'] == null ? undefined : ((value['correspondenceTables'] as Array<any>).map(CorrespondenceTableSummaryResourceToJSON)),
        'classificationVariants': value['classificationVariants'] == null ? undefined : ((value['classificationVariants'] as Array<any>).map(ClassificationVariantSummaryResourceToJSON)),
        'changelogs': value['changelogs'] == null ? undefined : ((value['changelogs'] as Array<any>).map(ChangelogResourceToJSON)),
        'levels': value['levels'] == null ? undefined : ((value['levels'] as Array<any>).map(LevelResourceToJSON)),
        'classificationItems': value['classificationItems'] == null ? undefined : ((value['classificationItems'] as Array<any>).map(ClassificationItemResourceToJSON)),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

