/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { ClassificationSummaryResource } from './ClassificationSummaryResource';
import {
    ClassificationSummaryResourceFromJSON,
    ClassificationSummaryResourceFromJSONTyped,
    ClassificationSummaryResourceToJSON,
    ClassificationSummaryResourceToJSONTyped,
} from './ClassificationSummaryResource';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ClassificationFamilyResource
 */
export interface ClassificationFamilyResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationFamilyResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationFamilyResource
     */
    id?: number;
    /**
     * 
     * @type {Array<ClassificationSummaryResource>}
     * @memberof ClassificationFamilyResource
     */
    classifications?: Array<ClassificationSummaryResource>;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof ClassificationFamilyResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof ClassificationFamilyResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof ClassificationFamilyResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the ClassificationFamilyResource interface.
 */
export function instanceOfClassificationFamilyResource(value: object): value is ClassificationFamilyResource {
    return true;
}

export function ClassificationFamilyResourceFromJSON(json: any): ClassificationFamilyResource {
    return ClassificationFamilyResourceFromJSONTyped(json, false);
}

export function ClassificationFamilyResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationFamilyResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'classifications': json['classifications'] == null ? undefined : ((json['classifications'] as Array<any>).map(ClassificationSummaryResourceFromJSON)),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function ClassificationFamilyResourceToJSON(json: any): ClassificationFamilyResource {
    return ClassificationFamilyResourceToJSONTyped(json, false);
}

export function ClassificationFamilyResourceToJSONTyped(value?: ClassificationFamilyResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'classifications': value['classifications'] == null ? undefined : ((value['classifications'] as Array<any>).map(ClassificationSummaryResourceToJSON)),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

