/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ClassificationSummaryResource
 */
export interface ClassificationSummaryResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationSummaryResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationSummaryResource
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassificationSummaryResource
     */
    classificationType?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationSummaryResource
     */
    classificationFamilyId?: number;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationSummaryResource
     */
    lastModified?: Date;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof ClassificationSummaryResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof ClassificationSummaryResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof ClassificationSummaryResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the ClassificationSummaryResource interface.
 */
export function instanceOfClassificationSummaryResource(value: object): value is ClassificationSummaryResource {
    return true;
}

export function ClassificationSummaryResourceFromJSON(json: any): ClassificationSummaryResource {
    return ClassificationSummaryResourceFromJSONTyped(json, false);
}

export function ClassificationSummaryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationSummaryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'classificationType': json['classificationType'] == null ? undefined : json['classificationType'],
        'classificationFamilyId': json['classificationFamilyId'] == null ? undefined : json['classificationFamilyId'],
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function ClassificationSummaryResourceToJSON(json: any): ClassificationSummaryResource {
    return ClassificationSummaryResourceToJSONTyped(json, false);
}

export function ClassificationSummaryResourceToJSONTyped(value?: ClassificationSummaryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'classificationType': value['classificationType'],
        'classificationFamilyId': value['classificationFamilyId'],
        'lastModified': value['lastModified'] == null ? value['lastModified'] : value['lastModified'].toISOString(),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

