/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ContactPersonResource } from './ContactPersonResource';
import {
    ContactPersonResourceFromJSON,
    ContactPersonResourceFromJSONTyped,
    ContactPersonResourceToJSON,
    ContactPersonResourceToJSONTyped,
} from './ContactPersonResource';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ClassificationVariantSummaryResource
 */
export interface ClassificationVariantSummaryResource {
    /**
     * 
     * @type {string}
     * @memberof ClassificationVariantSummaryResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassificationVariantSummaryResource
     */
    id?: number;
    /**
     * 
     * @type {ContactPersonResource}
     * @memberof ClassificationVariantSummaryResource
     */
    contactPerson?: ContactPersonResource;
    /**
     * 
     * @type {string}
     * @memberof ClassificationVariantSummaryResource
     */
    owningSection?: string;
    /**
     * 
     * @type {Date}
     * @memberof ClassificationVariantSummaryResource
     */
    lastModified?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationVariantSummaryResource
     */
    published?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof ClassificationVariantSummaryResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof ClassificationVariantSummaryResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof ClassificationVariantSummaryResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the ClassificationVariantSummaryResource interface.
 */
export function instanceOfClassificationVariantSummaryResource(value: object): value is ClassificationVariantSummaryResource {
    return true;
}

export function ClassificationVariantSummaryResourceFromJSON(json: any): ClassificationVariantSummaryResource {
    return ClassificationVariantSummaryResourceFromJSONTyped(json, false);
}

export function ClassificationVariantSummaryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationVariantSummaryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'contactPerson': json['contactPerson'] == null ? undefined : ContactPersonResourceFromJSON(json['contactPerson']),
        'owningSection': json['owningSection'] == null ? undefined : json['owningSection'],
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'published': json['published'] == null ? undefined : json['published'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function ClassificationVariantSummaryResourceToJSON(json: any): ClassificationVariantSummaryResource {
    return ClassificationVariantSummaryResourceToJSONTyped(json, false);
}

export function ClassificationVariantSummaryResourceToJSONTyped(value?: ClassificationVariantSummaryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'contactPerson': ContactPersonResourceToJSON(value['contactPerson']),
        'owningSection': value['owningSection'],
        'lastModified': value['lastModified'] == null ? value['lastModified'] : value['lastModified'].toISOString(),
        'published': value['published'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

