/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeChangeItem
 */
export interface CodeChangeItem {
    /**
     * 
     * @type {string}
     * @memberof CodeChangeItem
     */
    oldCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeChangeItem
     */
    oldName?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeChangeItem
     */
    oldShortName?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeChangeItem
     */
    newCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeChangeItem
     */
    newName?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeChangeItem
     */
    newShortName?: string;
    /**
     * 
     * @type {Date}
     * @memberof CodeChangeItem
     */
    changeOccurred?: Date;
}

/**
 * Check if a given object implements the CodeChangeItem interface.
 */
export function instanceOfCodeChangeItem(value: object): value is CodeChangeItem {
    return true;
}

export function CodeChangeItemFromJSON(json: any): CodeChangeItem {
    return CodeChangeItemFromJSONTyped(json, false);
}

export function CodeChangeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeChangeItem {
    if (json == null) {
        return json;
    }
    return {
        
        'oldCode': json['oldCode'] == null ? undefined : json['oldCode'],
        'oldName': json['oldName'] == null ? undefined : json['oldName'],
        'oldShortName': json['oldShortName'] == null ? undefined : json['oldShortName'],
        'newCode': json['newCode'] == null ? undefined : json['newCode'],
        'newName': json['newName'] == null ? undefined : json['newName'],
        'newShortName': json['newShortName'] == null ? undefined : json['newShortName'],
        'changeOccurred': json['changeOccurred'] == null ? undefined : (new Date(json['changeOccurred'])),
    };
}

export function CodeChangeItemToJSON(json: any): CodeChangeItem {
    return CodeChangeItemToJSONTyped(json, false);
}

export function CodeChangeItemToJSONTyped(value?: CodeChangeItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldCode': value['oldCode'],
        'oldName': value['oldName'],
        'oldShortName': value['oldShortName'],
        'newCode': value['newCode'],
        'newName': value['newName'],
        'newShortName': value['newShortName'],
        'changeOccurred': value['changeOccurred'] == null ? value['changeOccurred'] : value['changeOccurred'].toISOString().substring(0,10),
    };
}

