/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeItem
 */
export interface CodeItem {
    /**
     * 
     * @type {string}
     * @memberof CodeItem
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeItem
     */
    parentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeItem
     */
    level?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeItem
     */
    shortName?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeItem
     */
    presentationName?: string;
    /**
     * 
     * @type {Date}
     * @memberof CodeItem
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CodeItem
     */
    validTo?: Date;
    /**
     * 
     * @type {string}
     * @memberof CodeItem
     */
    notes?: string;
}

/**
 * Check if a given object implements the CodeItem interface.
 */
export function instanceOfCodeItem(value: object): value is CodeItem {
    return true;
}

export function CodeItemFromJSON(json: any): CodeItem {
    return CodeItemFromJSONTyped(json, false);
}

export function CodeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeItem {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'parentCode': json['parentCode'] == null ? undefined : json['parentCode'],
        'level': json['level'] == null ? undefined : json['level'],
        'name': json['name'] == null ? undefined : json['name'],
        'shortName': json['shortName'] == null ? undefined : json['shortName'],
        'presentationName': json['presentationName'] == null ? undefined : json['presentationName'],
        'validFrom': json['validFrom'] == null ? undefined : (new Date(json['validFrom'])),
        'validTo': json['validTo'] == null ? undefined : (new Date(json['validTo'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CodeItemToJSON(json: any): CodeItem {
    return CodeItemToJSONTyped(json, false);
}

export function CodeItemToJSONTyped(value?: CodeItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'parentCode': value['parentCode'],
        'level': value['level'],
        'name': value['name'],
        'shortName': value['shortName'],
        'presentationName': value['presentationName'],
        'validFrom': value['validFrom'] == null ? value['validFrom'] : value['validFrom'].toISOString().substring(0,10),
        'validTo': value['validTo'] == null ? value['validTo'] : value['validTo'].toISOString().substring(0,10),
        'notes': value['notes'],
    };
}

