/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClassificationFamilySummaryResource } from './ClassificationFamilySummaryResource';
import {
    ClassificationFamilySummaryResourceFromJSON,
    ClassificationFamilySummaryResourceFromJSONTyped,
    ClassificationFamilySummaryResourceToJSON,
    ClassificationFamilySummaryResourceToJSONTyped,
} from './ClassificationFamilySummaryResource';

/**
 * 
 * @export
 * @interface CollectionModelClassificationFamilySummaryResourceEmbedded
 */
export interface CollectionModelClassificationFamilySummaryResourceEmbedded {
    /**
     * 
     * @type {Array<ClassificationFamilySummaryResource>}
     * @memberof CollectionModelClassificationFamilySummaryResourceEmbedded
     */
    classificationFamilies?: Array<ClassificationFamilySummaryResource>;
}

/**
 * Check if a given object implements the CollectionModelClassificationFamilySummaryResourceEmbedded interface.
 */
export function instanceOfCollectionModelClassificationFamilySummaryResourceEmbedded(value: object): value is CollectionModelClassificationFamilySummaryResourceEmbedded {
    return true;
}

export function CollectionModelClassificationFamilySummaryResourceEmbeddedFromJSON(json: any): CollectionModelClassificationFamilySummaryResourceEmbedded {
    return CollectionModelClassificationFamilySummaryResourceEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelClassificationFamilySummaryResourceEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelClassificationFamilySummaryResourceEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'classificationFamilies': json['classificationFamilies'] == null ? undefined : ((json['classificationFamilies'] as Array<any>).map(ClassificationFamilySummaryResourceFromJSON)),
    };
}

export function CollectionModelClassificationFamilySummaryResourceEmbeddedToJSON(json: any): CollectionModelClassificationFamilySummaryResourceEmbedded {
    return CollectionModelClassificationFamilySummaryResourceEmbeddedToJSONTyped(json, false);
}

export function CollectionModelClassificationFamilySummaryResourceEmbeddedToJSONTyped(value?: CollectionModelClassificationFamilySummaryResourceEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classificationFamilies': value['classificationFamilies'] == null ? undefined : ((value['classificationFamilies'] as Array<any>).map(ClassificationFamilySummaryResourceToJSON)),
    };
}

