/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SsbSectionResource } from './SsbSectionResource';
import {
    SsbSectionResourceFromJSON,
    SsbSectionResourceFromJSONTyped,
    SsbSectionResourceToJSON,
    SsbSectionResourceToJSONTyped,
} from './SsbSectionResource';

/**
 * 
 * @export
 * @interface CollectionModelSsbSectionResourceEmbedded
 */
export interface CollectionModelSsbSectionResourceEmbedded {
    /**
     * 
     * @type {Array<SsbSectionResource>}
     * @memberof CollectionModelSsbSectionResourceEmbedded
     */
    ssbSections?: Array<SsbSectionResource>;
}

/**
 * Check if a given object implements the CollectionModelSsbSectionResourceEmbedded interface.
 */
export function instanceOfCollectionModelSsbSectionResourceEmbedded(value: object): value is CollectionModelSsbSectionResourceEmbedded {
    return true;
}

export function CollectionModelSsbSectionResourceEmbeddedFromJSON(json: any): CollectionModelSsbSectionResourceEmbedded {
    return CollectionModelSsbSectionResourceEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelSsbSectionResourceEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelSsbSectionResourceEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'ssbSections': json['ssbSections'] == null ? undefined : ((json['ssbSections'] as Array<any>).map(SsbSectionResourceFromJSON)),
    };
}

export function CollectionModelSsbSectionResourceEmbeddedToJSON(json: any): CollectionModelSsbSectionResourceEmbedded {
    return CollectionModelSsbSectionResourceEmbeddedToJSONTyped(json, false);
}

export function CollectionModelSsbSectionResourceEmbeddedToJSONTyped(value?: CollectionModelSsbSectionResourceEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssbSections': value['ssbSections'] == null ? undefined : ((value['ssbSections'] as Array<any>).map(SsbSectionResourceToJSON)),
    };
}

