/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionModelSsbSectionResourceEmbedded } from './CollectionModelSsbSectionResourceEmbedded';
import {
    CollectionModelSsbSectionResourceEmbeddedFromJSON,
    CollectionModelSsbSectionResourceEmbeddedFromJSONTyped,
    CollectionModelSsbSectionResourceEmbeddedToJSON,
    CollectionModelSsbSectionResourceEmbeddedToJSONTyped,
} from './CollectionModelSsbSectionResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelSsbSectionResource
 */
export interface CollectionModelSsbSectionResource {
    /**
     * 
     * @type {CollectionModelSsbSectionResourceEmbedded}
     * @memberof CollectionModelSsbSectionResource
     */
    embedded?: CollectionModelSsbSectionResourceEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelSsbSectionResource
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelSsbSectionResource interface.
 */
export function instanceOfCollectionModelSsbSectionResource(value: object): value is CollectionModelSsbSectionResource {
    return true;
}

export function CollectionModelSsbSectionResourceFromJSON(json: any): CollectionModelSsbSectionResource {
    return CollectionModelSsbSectionResourceFromJSONTyped(json, false);
}

export function CollectionModelSsbSectionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelSsbSectionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : CollectionModelSsbSectionResourceEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelSsbSectionResourceToJSON(json: any): CollectionModelSsbSectionResource {
    return CollectionModelSsbSectionResourceToJSONTyped(json, false);
}

export function CollectionModelSsbSectionResourceToJSONTyped(value?: CollectionModelSsbSectionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': CollectionModelSsbSectionResourceEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

