/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ChangelogResource } from './ChangelogResource';
import {
    ChangelogResourceFromJSON,
    ChangelogResourceFromJSONTyped,
    ChangelogResourceToJSON,
    ChangelogResourceToJSONTyped,
} from './ChangelogResource';
import type { ContactPersonResource } from './ContactPersonResource';
import {
    ContactPersonResourceFromJSON,
    ContactPersonResourceFromJSONTyped,
    ContactPersonResourceToJSON,
    ContactPersonResourceToJSONTyped,
} from './ContactPersonResource';
import type { LevelResource } from './LevelResource';
import {
    LevelResourceFromJSON,
    LevelResourceFromJSONTyped,
    LevelResourceToJSON,
    LevelResourceToJSONTyped,
} from './LevelResource';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { CorrespondenceMapResource } from './CorrespondenceMapResource';
import {
    CorrespondenceMapResourceFromJSON,
    CorrespondenceMapResourceFromJSONTyped,
    CorrespondenceMapResourceToJSON,
    CorrespondenceMapResourceToJSONTyped,
} from './CorrespondenceMapResource';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CorrespondenceTableResource
 */
export interface CorrespondenceTableResource {
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CorrespondenceTableResource
     */
    id?: number;
    /**
     * 
     * @type {ContactPersonResource}
     * @memberof CorrespondenceTableResource
     */
    contactPerson?: ContactPersonResource;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableResource
     */
    owningSection?: string;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableResource
     */
    source?: string;
    /**
     * 
     * @type {number}
     * @memberof CorrespondenceTableResource
     */
    sourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableResource
     */
    target?: string;
    /**
     * 
     * @type {number}
     * @memberof CorrespondenceTableResource
     */
    targetId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CorrespondenceTableResource
     */
    changeTable?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CorrespondenceTableResource
     */
    lastModified?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof CorrespondenceTableResource
     */
    published?: Array<string>;
    /**
     * 
     * @type {LevelResource}
     * @memberof CorrespondenceTableResource
     */
    sourceLevel?: LevelResource;
    /**
     * 
     * @type {LevelResource}
     * @memberof CorrespondenceTableResource
     */
    targetLevel?: LevelResource;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableResource
     */
    description?: string;
    /**
     * 
     * @type {Array<ChangelogResource>}
     * @memberof CorrespondenceTableResource
     */
    changelogs?: Array<ChangelogResource>;
    /**
     * 
     * @type {Array<CorrespondenceMapResource>}
     * @memberof CorrespondenceTableResource
     */
    correspondenceMaps?: Array<CorrespondenceMapResource>;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CorrespondenceTableResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof CorrespondenceTableResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof CorrespondenceTableResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the CorrespondenceTableResource interface.
 */
export function instanceOfCorrespondenceTableResource(value: object): value is CorrespondenceTableResource {
    return true;
}

export function CorrespondenceTableResourceFromJSON(json: any): CorrespondenceTableResource {
    return CorrespondenceTableResourceFromJSONTyped(json, false);
}

export function CorrespondenceTableResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrespondenceTableResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'contactPerson': json['contactPerson'] == null ? undefined : ContactPersonResourceFromJSON(json['contactPerson']),
        'owningSection': json['owningSection'] == null ? undefined : json['owningSection'],
        'source': json['source'] == null ? undefined : json['source'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'target': json['target'] == null ? undefined : json['target'],
        'targetId': json['targetId'] == null ? undefined : json['targetId'],
        'changeTable': json['changeTable'] == null ? undefined : json['changeTable'],
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'published': json['published'] == null ? undefined : json['published'],
        'sourceLevel': json['sourceLevel'] == null ? undefined : LevelResourceFromJSON(json['sourceLevel']),
        'targetLevel': json['targetLevel'] == null ? undefined : LevelResourceFromJSON(json['targetLevel']),
        'description': json['description'] == null ? undefined : json['description'],
        'changelogs': json['changelogs'] == null ? undefined : ((json['changelogs'] as Array<any>).map(ChangelogResourceFromJSON)),
        'correspondenceMaps': json['correspondenceMaps'] == null ? undefined : ((json['correspondenceMaps'] as Array<any>).map(CorrespondenceMapResourceFromJSON)),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function CorrespondenceTableResourceToJSON(json: any): CorrespondenceTableResource {
    return CorrespondenceTableResourceToJSONTyped(json, false);
}

export function CorrespondenceTableResourceToJSONTyped(value?: CorrespondenceTableResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'contactPerson': ContactPersonResourceToJSON(value['contactPerson']),
        'owningSection': value['owningSection'],
        'source': value['source'],
        'sourceId': value['sourceId'],
        'target': value['target'],
        'targetId': value['targetId'],
        'changeTable': value['changeTable'],
        'lastModified': value['lastModified'] == null ? value['lastModified'] : value['lastModified'].toISOString(),
        'published': value['published'],
        'sourceLevel': LevelResourceToJSON(value['sourceLevel']),
        'targetLevel': LevelResourceToJSON(value['targetLevel']),
        'description': value['description'],
        'changelogs': value['changelogs'] == null ? undefined : ((value['changelogs'] as Array<any>).map(ChangelogResourceToJSON)),
        'correspondenceMaps': value['correspondenceMaps'] == null ? undefined : ((value['correspondenceMaps'] as Array<any>).map(CorrespondenceMapResourceToJSON)),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

