/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorrespondenceMapResource
 */
export interface CorrespondenceMapResource {
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceMapResource
     */
    sourceCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceMapResource
     */
    sourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceMapResource
     */
    targetCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceMapResource
     */
    targetName?: string;
}

/**
 * Check if a given object implements the CorrespondenceMapResource interface.
 */
export function instanceOfCorrespondenceMapResource(value: object): value is CorrespondenceMapResource {
    return true;
}

export function CorrespondenceMapResourceFromJSON(json: any): CorrespondenceMapResource {
    return CorrespondenceMapResourceFromJSONTyped(json, false);
}

export function CorrespondenceMapResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrespondenceMapResource {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceCode': json['sourceCode'] == null ? undefined : json['sourceCode'],
        'sourceName': json['sourceName'] == null ? undefined : json['sourceName'],
        'targetCode': json['targetCode'] == null ? undefined : json['targetCode'],
        'targetName': json['targetName'] == null ? undefined : json['targetName'],
    };
}

export function CorrespondenceMapResourceToJSON(json: any): CorrespondenceMapResource {
    return CorrespondenceMapResourceToJSONTyped(json, false);
}

export function CorrespondenceMapResourceToJSONTyped(value?: CorrespondenceMapResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceCode': value['sourceCode'],
        'sourceName': value['sourceName'],
        'targetCode': value['targetCode'],
        'targetName': value['targetName'],
    };
}

