/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorrespondenceItem } from './CorrespondenceItem';
import {
    CorrespondenceItemFromJSON,
    CorrespondenceItemFromJSONTyped,
    CorrespondenceItemToJSON,
    CorrespondenceItemToJSONTyped,
} from './CorrespondenceItem';

/**
 * 
 * @export
 * @interface CorrespondenceItemList
 */
export interface CorrespondenceItemList {
    /**
     * 
     * @type {Array<CorrespondenceItem>}
     * @memberof CorrespondenceItemList
     */
    correspondenceItems?: Array<CorrespondenceItem>;
}

/**
 * Check if a given object implements the CorrespondenceItemList interface.
 */
export function instanceOfCorrespondenceItemList(value: object): value is CorrespondenceItemList {
    return true;
}

export function CorrespondenceItemListFromJSON(json: any): CorrespondenceItemList {
    return CorrespondenceItemListFromJSONTyped(json, false);
}

export function CorrespondenceItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrespondenceItemList {
    if (json == null) {
        return json;
    }
    return {
        
        'correspondenceItems': json['correspondenceItems'] == null ? undefined : ((json['correspondenceItems'] as Array<any>).map(CorrespondenceItemFromJSON)),
    };
}

export function CorrespondenceItemListToJSON(json: any): CorrespondenceItemList {
    return CorrespondenceItemListToJSONTyped(json, false);
}

export function CorrespondenceItemListToJSONTyped(value?: CorrespondenceItemList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correspondenceItems': value['correspondenceItems'] == null ? undefined : ((value['correspondenceItems'] as Array<any>).map(CorrespondenceItemToJSON)),
    };
}

