/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ContactPersonResource } from './ContactPersonResource';
import {
    ContactPersonResourceFromJSON,
    ContactPersonResourceFromJSONTyped,
    ContactPersonResourceToJSON,
    ContactPersonResourceToJSONTyped,
} from './ContactPersonResource';
import type { LevelResource } from './LevelResource';
import {
    LevelResourceFromJSON,
    LevelResourceFromJSONTyped,
    LevelResourceToJSON,
    LevelResourceToJSONTyped,
} from './LevelResource';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CorrespondenceTableSummaryResource
 */
export interface CorrespondenceTableSummaryResource {
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableSummaryResource
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CorrespondenceTableSummaryResource
     */
    id?: number;
    /**
     * 
     * @type {ContactPersonResource}
     * @memberof CorrespondenceTableSummaryResource
     */
    contactPerson?: ContactPersonResource;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableSummaryResource
     */
    owningSection?: string;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableSummaryResource
     */
    source?: string;
    /**
     * 
     * @type {number}
     * @memberof CorrespondenceTableSummaryResource
     */
    sourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof CorrespondenceTableSummaryResource
     */
    target?: string;
    /**
     * 
     * @type {number}
     * @memberof CorrespondenceTableSummaryResource
     */
    targetId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CorrespondenceTableSummaryResource
     */
    changeTable?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CorrespondenceTableSummaryResource
     */
    lastModified?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof CorrespondenceTableSummaryResource
     */
    published?: Array<string>;
    /**
     * 
     * @type {LevelResource}
     * @memberof CorrespondenceTableSummaryResource
     */
    sourceLevel?: LevelResource;
    /**
     * 
     * @type {LevelResource}
     * @memberof CorrespondenceTableSummaryResource
     */
    targetLevel?: LevelResource;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CorrespondenceTableSummaryResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof CorrespondenceTableSummaryResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {PageMetadata}
     * @memberof CorrespondenceTableSummaryResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the CorrespondenceTableSummaryResource interface.
 */
export function instanceOfCorrespondenceTableSummaryResource(value: object): value is CorrespondenceTableSummaryResource {
    return true;
}

export function CorrespondenceTableSummaryResourceFromJSON(json: any): CorrespondenceTableSummaryResource {
    return CorrespondenceTableSummaryResourceFromJSONTyped(json, false);
}

export function CorrespondenceTableSummaryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrespondenceTableSummaryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'contactPerson': json['contactPerson'] == null ? undefined : ContactPersonResourceFromJSON(json['contactPerson']),
        'owningSection': json['owningSection'] == null ? undefined : json['owningSection'],
        'source': json['source'] == null ? undefined : json['source'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'target': json['target'] == null ? undefined : json['target'],
        'targetId': json['targetId'] == null ? undefined : json['targetId'],
        'changeTable': json['changeTable'] == null ? undefined : json['changeTable'],
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'published': json['published'] == null ? undefined : json['published'],
        'sourceLevel': json['sourceLevel'] == null ? undefined : LevelResourceFromJSON(json['sourceLevel']),
        'targetLevel': json['targetLevel'] == null ? undefined : LevelResourceFromJSON(json['targetLevel']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function CorrespondenceTableSummaryResourceToJSON(json: any): CorrespondenceTableSummaryResource {
    return CorrespondenceTableSummaryResourceToJSONTyped(json, false);
}

export function CorrespondenceTableSummaryResourceToJSONTyped(value?: CorrespondenceTableSummaryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'contactPerson': ContactPersonResourceToJSON(value['contactPerson']),
        'owningSection': value['owningSection'],
        'source': value['source'],
        'sourceId': value['sourceId'],
        'target': value['target'],
        'targetId': value['targetId'],
        'changeTable': value['changeTable'],
        'lastModified': value['lastModified'] == null ? value['lastModified'] : value['lastModified'].toISOString(),
        'published': value['published'],
        'sourceLevel': LevelResourceToJSON(value['sourceLevel']),
        'targetLevel': LevelResourceToJSON(value['targetLevel']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        'page': PageMetadataToJSON(value['page']),
    };
}

