/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { KlassPagedResourcesClassificationSummaryResourceEmbedded } from './KlassPagedResourcesClassificationSummaryResourceEmbedded';
import {
    KlassPagedResourcesClassificationSummaryResourceEmbeddedFromJSON,
    KlassPagedResourcesClassificationSummaryResourceEmbeddedFromJSONTyped,
    KlassPagedResourcesClassificationSummaryResourceEmbeddedToJSON,
    KlassPagedResourcesClassificationSummaryResourceEmbeddedToJSONTyped,
} from './KlassPagedResourcesClassificationSummaryResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface KlassPagedResourcesClassificationSummaryResource
 */
export interface KlassPagedResourcesClassificationSummaryResource {
    /**
     * 
     * @type {KlassPagedResourcesClassificationSummaryResourceEmbedded}
     * @memberof KlassPagedResourcesClassificationSummaryResource
     */
    embedded?: KlassPagedResourcesClassificationSummaryResourceEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof KlassPagedResourcesClassificationSummaryResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof KlassPagedResourcesClassificationSummaryResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the KlassPagedResourcesClassificationSummaryResource interface.
 */
export function instanceOfKlassPagedResourcesClassificationSummaryResource(value: object): value is KlassPagedResourcesClassificationSummaryResource {
    return true;
}

export function KlassPagedResourcesClassificationSummaryResourceFromJSON(json: any): KlassPagedResourcesClassificationSummaryResource {
    return KlassPagedResourcesClassificationSummaryResourceFromJSONTyped(json, false);
}

export function KlassPagedResourcesClassificationSummaryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): KlassPagedResourcesClassificationSummaryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : KlassPagedResourcesClassificationSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function KlassPagedResourcesClassificationSummaryResourceToJSON(json: any): KlassPagedResourcesClassificationSummaryResource {
    return KlassPagedResourcesClassificationSummaryResourceToJSONTyped(json, false);
}

export function KlassPagedResourcesClassificationSummaryResourceToJSONTyped(value?: KlassPagedResourcesClassificationSummaryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': KlassPagedResourcesClassificationSummaryResourceEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

