/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { KlassPagedResourcesSearchResultResourceEmbedded } from './KlassPagedResourcesSearchResultResourceEmbedded';
import {
    KlassPagedResourcesSearchResultResourceEmbeddedFromJSON,
    KlassPagedResourcesSearchResultResourceEmbeddedFromJSONTyped,
    KlassPagedResourcesSearchResultResourceEmbeddedToJSON,
    KlassPagedResourcesSearchResultResourceEmbeddedToJSONTyped,
} from './KlassPagedResourcesSearchResultResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface KlassPagedResourcesSearchResultResource
 */
export interface KlassPagedResourcesSearchResultResource {
    /**
     * 
     * @type {KlassPagedResourcesSearchResultResourceEmbedded}
     * @memberof KlassPagedResourcesSearchResultResource
     */
    embedded?: KlassPagedResourcesSearchResultResourceEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof KlassPagedResourcesSearchResultResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof KlassPagedResourcesSearchResultResource
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the KlassPagedResourcesSearchResultResource interface.
 */
export function instanceOfKlassPagedResourcesSearchResultResource(value: object): value is KlassPagedResourcesSearchResultResource {
    return true;
}

export function KlassPagedResourcesSearchResultResourceFromJSON(json: any): KlassPagedResourcesSearchResultResource {
    return KlassPagedResourcesSearchResultResourceFromJSONTyped(json, false);
}

export function KlassPagedResourcesSearchResultResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): KlassPagedResourcesSearchResultResource {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : KlassPagedResourcesSearchResultResourceEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function KlassPagedResourcesSearchResultResourceToJSON(json: any): KlassPagedResourcesSearchResultResource {
    return KlassPagedResourcesSearchResultResourceToJSONTyped(json, false);
}

export function KlassPagedResourcesSearchResultResourceToJSONTyped(value?: KlassPagedResourcesSearchResultResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': KlassPagedResourcesSearchResultResourceEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

