/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClassificationSummaryResource } from './ClassificationSummaryResource';
import {
    ClassificationSummaryResourceFromJSON,
    ClassificationSummaryResourceFromJSONTyped,
    ClassificationSummaryResourceToJSON,
    ClassificationSummaryResourceToJSONTyped,
} from './ClassificationSummaryResource';

/**
 * 
 * @export
 * @interface KlassPagedResourcesClassificationSummaryResourceEmbedded
 */
export interface KlassPagedResourcesClassificationSummaryResourceEmbedded {
    /**
     * 
     * @type {Array<ClassificationSummaryResource>}
     * @memberof KlassPagedResourcesClassificationSummaryResourceEmbedded
     */
    classifications?: Array<ClassificationSummaryResource>;
}

/**
 * Check if a given object implements the KlassPagedResourcesClassificationSummaryResourceEmbedded interface.
 */
export function instanceOfKlassPagedResourcesClassificationSummaryResourceEmbedded(value: object): value is KlassPagedResourcesClassificationSummaryResourceEmbedded {
    return true;
}

export function KlassPagedResourcesClassificationSummaryResourceEmbeddedFromJSON(json: any): KlassPagedResourcesClassificationSummaryResourceEmbedded {
    return KlassPagedResourcesClassificationSummaryResourceEmbeddedFromJSONTyped(json, false);
}

export function KlassPagedResourcesClassificationSummaryResourceEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): KlassPagedResourcesClassificationSummaryResourceEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'classifications': json['classifications'] == null ? undefined : ((json['classifications'] as Array<any>).map(ClassificationSummaryResourceFromJSON)),
    };
}

export function KlassPagedResourcesClassificationSummaryResourceEmbeddedToJSON(json: any): KlassPagedResourcesClassificationSummaryResourceEmbedded {
    return KlassPagedResourcesClassificationSummaryResourceEmbeddedToJSONTyped(json, false);
}

export function KlassPagedResourcesClassificationSummaryResourceEmbeddedToJSONTyped(value?: KlassPagedResourcesClassificationSummaryResourceEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classifications': value['classifications'] == null ? undefined : ((value['classifications'] as Array<any>).map(ClassificationSummaryResourceToJSON)),
    };
}

