/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResultResource } from './SearchResultResource';
import {
    SearchResultResourceFromJSON,
    SearchResultResourceFromJSONTyped,
    SearchResultResourceToJSON,
    SearchResultResourceToJSONTyped,
} from './SearchResultResource';

/**
 * 
 * @export
 * @interface KlassPagedResourcesSearchResultResourceEmbedded
 */
export interface KlassPagedResourcesSearchResultResourceEmbedded {
    /**
     * 
     * @type {Array<SearchResultResource>}
     * @memberof KlassPagedResourcesSearchResultResourceEmbedded
     */
    searchResults?: Array<SearchResultResource>;
}

/**
 * Check if a given object implements the KlassPagedResourcesSearchResultResourceEmbedded interface.
 */
export function instanceOfKlassPagedResourcesSearchResultResourceEmbedded(value: object): value is KlassPagedResourcesSearchResultResourceEmbedded {
    return true;
}

export function KlassPagedResourcesSearchResultResourceEmbeddedFromJSON(json: any): KlassPagedResourcesSearchResultResourceEmbedded {
    return KlassPagedResourcesSearchResultResourceEmbeddedFromJSONTyped(json, false);
}

export function KlassPagedResourcesSearchResultResourceEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): KlassPagedResourcesSearchResultResourceEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'searchResults': json['searchResults'] == null ? undefined : ((json['searchResults'] as Array<any>).map(SearchResultResourceFromJSON)),
    };
}

export function KlassPagedResourcesSearchResultResourceEmbeddedToJSON(json: any): KlassPagedResourcesSearchResultResourceEmbedded {
    return KlassPagedResourcesSearchResultResourceEmbeddedToJSONTyped(json, false);
}

export function KlassPagedResourcesSearchResultResourceEmbeddedToJSONTyped(value?: KlassPagedResourcesSearchResultResourceEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchResults': value['searchResults'] == null ? undefined : ((value['searchResults'] as Array<any>).map(SearchResultResourceToJSON)),
    };
}

