/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LevelResource
 */
export interface LevelResource {
    /**
     * 
     * @type {number}
     * @memberof LevelResource
     */
    levelNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof LevelResource
     */
    levelName?: string;
}

/**
 * Check if a given object implements the LevelResource interface.
 */
export function instanceOfLevelResource(value: object): value is LevelResource {
    return true;
}

export function LevelResourceFromJSON(json: any): LevelResource {
    return LevelResourceFromJSONTyped(json, false);
}

export function LevelResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelResource {
    if (json == null) {
        return json;
    }
    return {
        
        'levelNumber': json['levelNumber'] == null ? undefined : json['levelNumber'],
        'levelName': json['levelName'] == null ? undefined : json['levelName'],
    };
}

export function LevelResourceToJSON(json: any): LevelResource {
    return LevelResourceToJSONTyped(json, false);
}

export function LevelResourceToJSONTyped(value?: LevelResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'levelNumber': value['levelNumber'],
        'levelName': value['levelName'],
    };
}

