/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageMetadata
 */
export interface PageMetadata {
    /**
     * 
     * @type {number}
     * @memberof PageMetadata
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMetadata
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMetadata
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMetadata
     */
    number?: number;
}

/**
 * Check if a given object implements the PageMetadata interface.
 */
export function instanceOfPageMetadata(value: object): value is PageMetadata {
    return true;
}

export function PageMetadataFromJSON(json: any): PageMetadata {
    return PageMetadataFromJSONTyped(json, false);
}

export function PageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'number': json['number'] == null ? undefined : json['number'],
    };
}

export function PageMetadataToJSON(json: any): PageMetadata {
    return PageMetadataToJSONTyped(json, false);
}

export function PageMetadataToJSONTyped(value?: PageMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'number': value['number'],
    };
}

