/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface RepresentationModelObject
 */
export interface RepresentationModelObject {
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof RepresentationModelObject
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the RepresentationModelObject interface.
 */
export function instanceOfRepresentationModelObject(value: object): value is RepresentationModelObject {
    return true;
}

export function RepresentationModelObjectFromJSON(json: any): RepresentationModelObject {
    return RepresentationModelObjectFromJSONTyped(json, false);
}

export function RepresentationModelObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepresentationModelObject {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function RepresentationModelObjectToJSON(json: any): RepresentationModelObject {
    return RepresentationModelObjectToJSONTyped(json, false);
}

export function RepresentationModelObjectToJSONTyped(value?: RepresentationModelObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

