/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { ClassificationVariantSummaryResourceEmbedded } from './ClassificationVariantSummaryResourceEmbedded';
import {
    ClassificationVariantSummaryResourceEmbeddedFromJSON,
    ClassificationVariantSummaryResourceEmbeddedFromJSONTyped,
    ClassificationVariantSummaryResourceEmbeddedToJSON,
    ClassificationVariantSummaryResourceEmbeddedToJSONTyped,
} from './ClassificationVariantSummaryResourceEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface SsbSectionResource
 */
export interface SsbSectionResource {
    /**
     * 
     * @type {ClassificationVariantSummaryResourceEmbedded}
     * @memberof SsbSectionResource
     */
    embedded?: ClassificationVariantSummaryResourceEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof SsbSectionResource
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {string}
     * @memberof SsbSectionResource
     */
    name?: string;
    /**
     * 
     * @type {PageMetadata}
     * @memberof SsbSectionResource
     */
    page?: PageMetadata;
    /**
     * 
     * @type {number}
     * @memberof SsbSectionResource
     */
    id?: number;
}

/**
 * Check if a given object implements the SsbSectionResource interface.
 */
export function instanceOfSsbSectionResource(value: object): value is SsbSectionResource {
    return true;
}

export function SsbSectionResourceFromJSON(json: any): SsbSectionResource {
    return SsbSectionResourceFromJSONTyped(json, false);
}

export function SsbSectionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SsbSectionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : ClassificationVariantSummaryResourceEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SsbSectionResourceToJSON(json: any): SsbSectionResource {
    return SsbSectionResourceToJSONTyped(json, false);
}

export function SsbSectionResourceToJSONTyped(value?: SsbSectionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': ClassificationVariantSummaryResourceEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'name': value['name'],
        'page': PageMetadataToJSON(value['page']),
        'id': value['id'],
    };
}

