/* tslint:disable */
/* eslint-disable */
/**
 * Public Variable Definitions API
 * Public Variable Definitions
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenderedVariableDefinitionUnitTypesInner
 */
export interface RenderedVariableDefinitionUnitTypesInner {
    /**
     * 
     * @type {string}
     * @memberof RenderedVariableDefinitionUnitTypesInner
     */
    referenceUri: string;
    /**
     * 
     * @type {string}
     * @memberof RenderedVariableDefinitionUnitTypesInner
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderedVariableDefinitionUnitTypesInner
     */
    title?: string | null;
}

/**
 * Check if a given object implements the RenderedVariableDefinitionUnitTypesInner interface.
 */
export function instanceOfRenderedVariableDefinitionUnitTypesInner(value: object): value is RenderedVariableDefinitionUnitTypesInner {
    if (!('referenceUri' in value) || value['referenceUri'] === undefined) return false;
    return true;
}

export function RenderedVariableDefinitionUnitTypesInnerFromJSON(json: any): RenderedVariableDefinitionUnitTypesInner {
    return RenderedVariableDefinitionUnitTypesInnerFromJSONTyped(json, false);
}

export function RenderedVariableDefinitionUnitTypesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderedVariableDefinitionUnitTypesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'referenceUri': json['reference_uri'],
        'code': json['code'] == null ? undefined : json['code'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function RenderedVariableDefinitionUnitTypesInnerToJSON(json: any): RenderedVariableDefinitionUnitTypesInner {
    return RenderedVariableDefinitionUnitTypesInnerToJSONTyped(json, false);
}

export function RenderedVariableDefinitionUnitTypesInnerToJSONTyped(value?: RenderedVariableDefinitionUnitTypesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference_uri': value['referenceUri'],
        'code': value['code'],
        'title': value['title'],
    };
}

