exclude: (__snapshots__|\.snap$|src/libs/data-access/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: Biome format
        name: biome format
        entry: pnpm exec biome format --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        # Taken from https://github.com/biomejs/pre-commit?tab=readme-ov-file#using-biome-with-a-local-pre-commit-hook
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
      - id: Biome lint
        name: biome lint
        entry: pnpm exec biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        # Taken from https://github.com/biomejs/pre-commit?tab=readme-ov-file#using-biome-with-a-local-pre-commit-hook
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
