allowBuilds:
  "@nestjs/core": false
  "@openapitools/openapi-generator-cli": false
  "@parcel/watcher": true
  esbuild: false
  sharp: true
minimumReleaseAge: 10080
overrides:
  # This transitive dependency is locked to ensure the coverage tool @bgotink/playwright-coverage
  # uses a compatible Playwright API
  playwright-core: "catalog:playwright"

catalogs:
  playwright:
    "@playwright/test": "1.63.0"
    "playwright-core": "1.63.0"
