allowBuilds:
  '@nestjs/core': false
  '@openapitools/openapi-generator-cli': false
  '@parcel/watcher': true
  esbuild: false
  sharp: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@playwright/test@1.61.1'
  - playwright-core@1.61.1
  - playwright@1.61.1
