sonar.projectKey=statisticsnorway_ssb-dataportal
sonar.organization=statisticsnorway

sonar.projectName=ssb-dataportal
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/e2e/**/*

sonar.coverage.exclusions=**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
