sonar.projectKey=statisticsnorway_ssb-dataportal
sonar.organization=statisticsnorway

sonar.projectName=ssb-dataportal
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=src/libs/data-access/**,src/static-data/**,**/*.yaml
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/e2e/**/*

sonar.javascript.lcov.reportPaths=coverage/lcov.info,results/e2e-coverage/coverage.lcov
