apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: dapla-metadata
  name: dataportalen
  namespace: dapla-metadata
  annotations:
    # Allow nextjs to create cache directories inside /app
    nais.io/read-only-file-system: "false"
spec:
  ingresses:
    - https://dataportal.ssb.no
  port: 3000
  accessPolicy:
    outbound:
      rules:
        - application: metadata-api-gateway
        - application: klass
      external:
        - host: auth.ssb.no
  login:
    provider: openid
    enforce:
      enabled: true
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: 10m
      memory: 300mi
  envFrom:
    - secret: dataportalen
  env:
    - name: VARDEF_BASE_PATH
      value: http://metadata-api-gateway
    - name: VARDEF_USE_STATIC_DATA
      value: "false"
    - name: VARDEF_USE_M2M_TOKEN
      value: "true"
    - name: KEYCLOAK_HOST
      value: https://auth.ssb.no
    - name: KLASS_BASE_PATH
      value: http://klass/api/klass/v1
    - name: KLASS_USE_STATIC_DATA
      value: "false"
    - name: VARDEF_API_DOCS_URL
      value: "https://metadata.ssb.no/docs/swagger/variable-definitions"
    - name: DAPLA_LAB_VARDEF_URL
      value: "https://lab.dapla.ssb.no/launcher/dapla-lab-standard/vardef-forvaltning"
    - name: LOG_LEVEL
      value: "info"
