/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClassificationFamilyResource,
  CollectionModelClassificationFamilySummaryResource,
  Versions404Response,
} from '../models/index';
import {
    ClassificationFamilyResourceFromJSON,
    ClassificationFamilyResourceToJSON,
    CollectionModelClassificationFamilySummaryResourceFromJSON,
    CollectionModelClassificationFamilySummaryResourceToJSON,
    Versions404ResponseFromJSON,
    Versions404ResponseToJSON,
} from '../models/index';

export interface ClassificationFamiliesRequest {
    ssbSection?: string;
    includeCodelists?: boolean;
    language?: ClassificationFamiliesLanguageEnum;
}

export interface ClassificationFamilyRequest {
    id: number;
    ssbSection?: string;
    includeCodelists?: boolean;
    language?: ClassificationFamilyLanguageEnum;
}

/**
 * ClassificationFamiliesApi - interface
 * 
 * @export
 * @interface ClassificationFamiliesApiInterface
 */
export interface ClassificationFamiliesApiInterface {
    /**
     * 
     * @param {string} [ssbSection] 
     * @param {boolean} [includeCodelists] 
     * @param {'NB' | 'NN' | 'EN'} [language] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassificationFamiliesApiInterface
     */
    classificationFamiliesRaw(requestParameters: ClassificationFamiliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelClassificationFamilySummaryResource>>;

    /**
     */
    classificationFamilies(requestParameters: ClassificationFamiliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelClassificationFamilySummaryResource>;

    /**
     * 
     * @param {number} id 
     * @param {string} [ssbSection] 
     * @param {boolean} [includeCodelists] 
     * @param {'NB' | 'NN' | 'EN'} [language] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassificationFamiliesApiInterface
     */
    classificationFamilyRaw(requestParameters: ClassificationFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassificationFamilyResource>>;

    /**
     */
    classificationFamily(requestParameters: ClassificationFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassificationFamilyResource>;

}

/**
 * 
 */
export class ClassificationFamiliesApi extends runtime.BaseAPI implements ClassificationFamiliesApiInterface {

    /**
     */
    async classificationFamiliesRaw(requestParameters: ClassificationFamiliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelClassificationFamilySummaryResource>> {
        const queryParameters: any = {};

        if (requestParameters['ssbSection'] != null) {
            queryParameters['ssbSection'] = requestParameters['ssbSection'];
        }

        if (requestParameters['includeCodelists'] != null) {
            queryParameters['includeCodelists'] = requestParameters['includeCodelists'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/classificationfamilies`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelClassificationFamilySummaryResourceFromJSON(jsonValue));
    }

    /**
     */
    async classificationFamilies(requestParameters: ClassificationFamiliesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelClassificationFamilySummaryResource> {
        const response = await this.classificationFamiliesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async classificationFamilyRaw(requestParameters: ClassificationFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassificationFamilyResource>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling classificationFamily().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ssbSection'] != null) {
            queryParameters['ssbSection'] = requestParameters['ssbSection'];
        }

        if (requestParameters['includeCodelists'] != null) {
            queryParameters['includeCodelists'] = requestParameters['includeCodelists'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/classificationfamilies/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassificationFamilyResourceFromJSON(jsonValue));
    }

    /**
     */
    async classificationFamily(requestParameters: ClassificationFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassificationFamilyResource> {
        const response = await this.classificationFamilyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ClassificationFamiliesLanguageEnum = {
    NB: 'NB',
    NN: 'NN',
    EN: 'EN'
} as const;
export type ClassificationFamiliesLanguageEnum = typeof ClassificationFamiliesLanguageEnum[keyof typeof ClassificationFamiliesLanguageEnum];
/**
 * @export
 */
export const ClassificationFamilyLanguageEnum = {
    NB: 'NB',
    NN: 'NN',
    EN: 'EN'
} as const;
export type ClassificationFamilyLanguageEnum = typeof ClassificationFamilyLanguageEnum[keyof typeof ClassificationFamilyLanguageEnum];
