/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClassificationResource,
  KlassPagedResourcesClassificationSummaryResource,
  Versions404Response,
} from '../models/index';
import {
    ClassificationResourceFromJSON,
    ClassificationResourceToJSON,
    KlassPagedResourcesClassificationSummaryResourceFromJSON,
    KlassPagedResourcesClassificationSummaryResourceToJSON,
    Versions404ResponseFromJSON,
    Versions404ResponseToJSON,
} from '../models/index';

export interface ClassificationRequest {
    id: number;
    language?: ClassificationLanguageEnum;
    includeFuture?: boolean;
}

export interface ClassificationsRequest {
    includeCodelists?: boolean;
    changedSince?: Date;
}

/**
 * ClassificationsApi - interface
 * 
 * @export
 * @interface ClassificationsApiInterface
 */
export interface ClassificationsApiInterface {
    /**
     * 
     * @param {number} id 
     * @param {'NB' | 'NN' | 'EN'} [language] 
     * @param {boolean} [includeFuture] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassificationsApiInterface
     */
    classificationRaw(requestParameters: ClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassificationResource>>;

    /**
     */
    classification(requestParameters: ClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassificationResource>;

    /**
     * 
     * @param {boolean} [includeCodelists] 
     * @param {Date} [changedSince] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassificationsApiInterface
     */
    classificationsRaw(requestParameters: ClassificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KlassPagedResourcesClassificationSummaryResource>>;

    /**
     */
    classifications(requestParameters: ClassificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KlassPagedResourcesClassificationSummaryResource>;

}

/**
 * 
 */
export class ClassificationsApi extends runtime.BaseAPI implements ClassificationsApiInterface {

    /**
     */
    async classificationRaw(requestParameters: ClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassificationResource>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling classification().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['includeFuture'] != null) {
            queryParameters['includeFuture'] = requestParameters['includeFuture'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/classifications/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassificationResourceFromJSON(jsonValue));
    }

    /**
     */
    async classification(requestParameters: ClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassificationResource> {
        const response = await this.classificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async classificationsRaw(requestParameters: ClassificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KlassPagedResourcesClassificationSummaryResource>> {
        const queryParameters: any = {};

        if (requestParameters['includeCodelists'] != null) {
            queryParameters['includeCodelists'] = requestParameters['includeCodelists'];
        }

        if (requestParameters['changedSince'] != null) {
            queryParameters['changedSince'] = requestParameters['changedSince'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/classifications`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KlassPagedResourcesClassificationSummaryResourceFromJSON(jsonValue));
    }

    /**
     */
    async classifications(requestParameters: ClassificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KlassPagedResourcesClassificationSummaryResource> {
        const response = await this.classificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ClassificationLanguageEnum = {
    NB: 'NB',
    NN: 'NN',
    EN: 'EN'
} as const;
export type ClassificationLanguageEnum = typeof ClassificationLanguageEnum[keyof typeof ClassificationLanguageEnum];
