/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  KlassPagedResourcesSearchResultResource,
  ProblemDetail,
} from '../models/index';
import {
    KlassPagedResourcesSearchResultResourceFromJSON,
    KlassPagedResourcesSearchResultResourceToJSON,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/index';

export interface SearchRequest {
    query: string;
    ssbSection?: string;
    includeCodelists?: boolean;
}

/**
 * SearchApi - interface
 * 
 * @export
 * @interface SearchApiInterface
 */
export interface SearchApiInterface {
    /**
     * 
     * @param {string} query 
     * @param {string} [ssbSection] 
     * @param {boolean} [includeCodelists] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KlassPagedResourcesSearchResultResource>>;

    /**
     */
    search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KlassPagedResourcesSearchResultResource>;

}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI implements SearchApiInterface {

    /**
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KlassPagedResourcesSearchResultResource>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['ssbSection'] != null) {
            queryParameters['ssbSection'] = requestParameters['ssbSection'];
        }

        if (requestParameters['includeCodelists'] != null) {
            queryParameters['includeCodelists'] = requestParameters['includeCodelists'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/klass/v1/classifications/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KlassPagedResourcesSearchResultResourceFromJSON(jsonValue));
    }

    /**
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KlassPagedResourcesSearchResultResource> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
