/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelSsbSectionResource,
  Versions404Response,
} from '../models/index';
import {
    CollectionModelSsbSectionResourceFromJSON,
    CollectionModelSsbSectionResourceToJSON,
    Versions404ResponseFromJSON,
    Versions404ResponseToJSON,
} from '../models/index';

/**
 * SSBSectionsApi - interface
 * 
 * @export
 * @interface SSBSectionsApiInterface
 */
export interface SSBSectionsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SSBSectionsApiInterface
     */
    ssbsectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelSsbSectionResource>>;

    /**
     */
    ssbsections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelSsbSectionResource>;

}

/**
 * 
 */
export class SSBSectionsApi extends runtime.BaseAPI implements SSBSectionsApiInterface {

    /**
     */
    async ssbsectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelSsbSectionResource>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/ssbsections`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelSsbSectionResourceFromJSON(jsonValue));
    }

    /**
     */
    async ssbsections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelSsbSectionResource> {
        const response = await this.ssbsectionsRaw(initOverrides);
        return await response.value();
    }

}
