/* tslint:disable */
/* eslint-disable */
/**
 * Klass
 * Klass is Statistics Norway\'s system for documentation of classifications and code lists. This API provides read-only access to classifications and code lists.  Classifications are \"official\", and in a classification, the categories at each level must be mutually exclusive and complete, i.e. the classification contains all categories that belong to the area covered by the classification. Code lists are not \"official\". They may be adapted to a one particular statistic and do not have to be mutually exclusive or complete. 
 *
 * The version of the OpenAPI document: 1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClassificationVersionResource,
  Versions404Response,
} from '../models/index';
import {
    ClassificationVersionResourceFromJSON,
    ClassificationVersionResourceToJSON,
    Versions404ResponseFromJSON,
    Versions404ResponseToJSON,
} from '../models/index';

export interface VersionsRequest {
    id: number;
    language?: VersionsLanguageEnum;
    includeFuture?: boolean;
}

/**
 * VersionsApi - interface
 * 
 * @export
 * @interface VersionsApiInterface
 */
export interface VersionsApiInterface {
    /**
     * 
     * @param {number} id 
     * @param {'NB' | 'NN' | 'EN'} [language] 
     * @param {boolean} [includeFuture] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VersionsApiInterface
     */
    versionsRaw(requestParameters: VersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassificationVersionResource>>;

    /**
     */
    versions(requestParameters: VersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassificationVersionResource>;

}

/**
 * 
 */
export class VersionsApi extends runtime.BaseAPI implements VersionsApiInterface {

    /**
     */
    async versionsRaw(requestParameters: VersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassificationVersionResource>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling versions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['includeFuture'] != null) {
            queryParameters['includeFuture'] = requestParameters['includeFuture'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/versions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassificationVersionResourceFromJSON(jsonValue));
    }

    /**
     */
    async versions(requestParameters: VersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassificationVersionResource> {
        const response = await this.versionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const VersionsLanguageEnum = {
    NB: 'NB',
    NN: 'NN',
    EN: 'EN'
} as const;
export type VersionsLanguageEnum = typeof VersionsLanguageEnum[keyof typeof VersionsLanguageEnum];
