/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create a Data File. A Data File is a logically defined blob of data from a file system or object storage. Its file path shall follow Dapla's naming conventions.
 * @export
 * @interface CreateDaplaDataFile
 */
export interface CreateDaplaDataFile {
    /**
     * 
     * @type {string}
     * @memberof CreateDaplaDataFile
     */
    file_path: string;
}

/**
 * Check if a given object implements the CreateDaplaDataFile interface.
 */
export function instanceOfCreateDaplaDataFile(value: object): value is CreateDaplaDataFile {
    if (!('file_path' in value) || value['file_path'] === undefined) return false;
    return true;
}

export function CreateDaplaDataFileFromJSON(json: any): CreateDaplaDataFile {
    return CreateDaplaDataFileFromJSONTyped(json, false);
}

export function CreateDaplaDataFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDaplaDataFile {
    if (json == null) {
        return json;
    }
    return {
        
        'file_path': json['file_path'],
    };
}

export function CreateDaplaDataFileToJSON(json: any): CreateDaplaDataFile {
    return CreateDaplaDataFileToJSONTyped(json, false);
}

export function CreateDaplaDataFileToJSONTyped(value?: CreateDaplaDataFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_path': value['file_path'],
    };
}

