/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileType } from './FileType';
import {
    FileTypeFromJSON,
    FileTypeFromJSONTyped,
    FileTypeToJSON,
    FileTypeToJSONTyped,
} from './FileType';
import type { StorageCategory } from './StorageCategory';
import {
    StorageCategoryFromJSON,
    StorageCategoryFromJSONTyped,
    StorageCategoryToJSON,
    StorageCategoryToJSONTyped,
} from './StorageCategory';
import type { Assessment } from './Assessment';
import {
    AssessmentFromJSON,
    AssessmentFromJSONTyped,
    AssessmentToJSON,
    AssessmentToJSONTyped,
} from './Assessment';
import type { DatasetState } from './DatasetState';
import {
    DatasetStateFromJSON,
    DatasetStateFromJSONTyped,
    DatasetStateToJSON,
    DatasetStateToJSONTyped,
} from './DatasetState';
import type { DataProductType } from './DataProductType';
import {
    DataProductTypeFromJSON,
    DataProductTypeFromJSONTyped,
    DataProductTypeToJSON,
    DataProductTypeToJSONTyped,
} from './DataProductType';

/**
 * External representation of a Data File. A Data File is a logically defined blob of data from a file system or object storage. Its file path shall follow Dapla's naming conventions. This model is used to represent a data file to clients.
 * @export
 * @interface DaplaDataFileDTO
 */
export interface DaplaDataFileDTO {
    /**
     * The file path of the data file. This is the unique identifier of the data file.
     * @type {string}
     * @memberof DaplaDataFileDTO
     */
    file_path: string;
    /**
     * The name of the storage location where the data file is stored. In the case of object storage, this is the name of the bucket.
     * @type {string}
     * @memberof DaplaDataFileDTO
     */
    storage_location_name?: string | null;
    /**
     * 
     * @type {FileType}
     * @memberof DaplaDataFileDTO
     */
    file_type?: FileType | null;
    /**
     * The last modified timestamp of the data file, as reported by the storage provider.
     * @type {Date}
     * @memberof DaplaDataFileDTO
     */
    data_last_modified_at?: Date | null;
    /**
     * The checksum of the data file, as reported by the storage provider. This may be used to detect changes in the data file.
     * @type {string}
     * @memberof DaplaDataFileDTO
     */
    checksum?: string | null;
    /**
     * A short description of the data file, sourced from the file path. \[Defined in the Dapla Manual.\](https://manual.dapla.ssb.no/statistikkere/navnestandard.html#filnavn)
     * @type {string}
     * @memberof DaplaDataFileDTO
     */
    short_description?: string | null;
    /**
     * 
     * @type {DataProductType}
     * @memberof DaplaDataFileDTO
     */
    product_type?: DataProductType | null;
    /**
     * The identifier of the product this data file belongs to, sourced from the file path. If this is a \[DataProductType.STATISTIC_PRODUCT\], it must match a short name defined in the Statistic Register. If it is a \[DataProductType.OTHER_DATA_PRODUCT\], it has no canonical definition, but must end with \`_data\`.
     * @type {string}
     * @memberof DaplaDataFileDTO
     */
    product_short_name?: string | null;
    /**
     * 
     * @type {StorageCategory}
     * @memberof DaplaDataFileDTO
     */
    storage_category?: StorageCategory | null;
    /**
     * 
     * @type {Assessment}
     * @memberof DaplaDataFileDTO
     */
    assessment?: Assessment | null;
    /**
     * 
     * @type {DatasetState}
     * @memberof DaplaDataFileDTO
     */
    dataset_state?: DatasetState | null;
    /**
     * The version of the data file. Versions correspond to structural changes in the data file. \[Defined in the Dapla Manual.\](https://manual.dapla.ssb.no/statistikkere/navnestandard.html#versjonering-av-datasett)
     * @type {number}
     * @memberof DaplaDataFileDTO
     */
    data_file_version?: number | null;
    /**
     * The start date of the time period the data file covers, sourced from the file path.
     * @type {Date}
     * @memberof DaplaDataFileDTO
     */
    contains_data_from?: Date | null;
    /**
     * The end date of the time period the data file covers, sourced from the file path.
     * @type {Date}
     * @memberof DaplaDataFileDTO
     */
    contains_data_until?: Date | null;
    /**
     * The uniform name of the Dapla team which owns the data file.
     * @type {string}
     * @memberof DaplaDataFileDTO
     */
    owner?: string | null;
}



/**
 * Check if a given object implements the DaplaDataFileDTO interface.
 */
export function instanceOfDaplaDataFileDTO(value: object): value is DaplaDataFileDTO {
    if (!('file_path' in value) || value['file_path'] === undefined) return false;
    return true;
}

export function DaplaDataFileDTOFromJSON(json: any): DaplaDataFileDTO {
    return DaplaDataFileDTOFromJSONTyped(json, false);
}

export function DaplaDataFileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DaplaDataFileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'file_path': json['file_path'],
        'storage_location_name': json['storage_location_name'] == null ? undefined : json['storage_location_name'],
        'file_type': json['file_type'] == null ? undefined : FileTypeFromJSON(json['file_type']),
        'data_last_modified_at': json['data_last_modified_at'] == null ? undefined : (new Date(json['data_last_modified_at'])),
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'short_description': json['short_description'] == null ? undefined : json['short_description'],
        'product_type': json['product_type'] == null ? undefined : DataProductTypeFromJSON(json['product_type']),
        'product_short_name': json['product_short_name'] == null ? undefined : json['product_short_name'],
        'storage_category': json['storage_category'] == null ? undefined : StorageCategoryFromJSON(json['storage_category']),
        'assessment': json['assessment'] == null ? undefined : AssessmentFromJSON(json['assessment']),
        'dataset_state': json['dataset_state'] == null ? undefined : DatasetStateFromJSON(json['dataset_state']),
        'data_file_version': json['data_file_version'] == null ? undefined : json['data_file_version'],
        'contains_data_from': json['contains_data_from'] == null ? undefined : (new Date(json['contains_data_from'])),
        'contains_data_until': json['contains_data_until'] == null ? undefined : (new Date(json['contains_data_until'])),
        'owner': json['owner'] == null ? undefined : json['owner'],
    };
}

export function DaplaDataFileDTOToJSON(json: any): DaplaDataFileDTO {
    return DaplaDataFileDTOToJSONTyped(json, false);
}

export function DaplaDataFileDTOToJSONTyped(value?: DaplaDataFileDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_path': value['file_path'],
        'storage_location_name': value['storage_location_name'],
        'file_type': FileTypeToJSON(value['file_type']),
        'data_last_modified_at': value['data_last_modified_at'] == null ? value['data_last_modified_at'] : value['data_last_modified_at'].toISOString(),
        'checksum': value['checksum'],
        'short_description': value['short_description'],
        'product_type': DataProductTypeToJSON(value['product_type']),
        'product_short_name': value['product_short_name'],
        'storage_category': StorageCategoryToJSON(value['storage_category']),
        'assessment': AssessmentToJSON(value['assessment']),
        'dataset_state': DatasetStateToJSON(value['dataset_state']),
        'data_file_version': value['data_file_version'],
        'contains_data_from': value['contains_data_from'] == null ? value['contains_data_from'] : value['contains_data_from'].toISOString(),
        'contains_data_until': value['contains_data_until'] == null ? value['contains_data_until'] : value['contains_data_until'].toISOString(),
        'owner': value['owner'],
    };
}

