/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DaplaDataFileDTO } from './DaplaDataFileDTO';
import {
    DaplaDataFileDTOFromJSON,
    DaplaDataFileDTOFromJSONTyped,
    DaplaDataFileDTOToJSON,
    DaplaDataFileDTOToJSONTyped,
} from './DaplaDataFileDTO';

/**
 * 
 * @export
 * @interface DaplaDataFilePageResponse
 */
export interface DaplaDataFilePageResponse {
    /**
     * 
     * @type {Array<DaplaDataFileDTO>}
     * @memberof DaplaDataFilePageResponse
     */
    data_files: Array<DaplaDataFileDTO>;
    /**
     * 
     * @type {number}
     * @memberof DaplaDataFilePageResponse
     */
    total_data_files: number;
    /**
     * 
     * @type {number}
     * @memberof DaplaDataFilePageResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DaplaDataFilePageResponse
     */
    page_size: number;
    /**
     * 
     * @type {boolean}
     * @memberof DaplaDataFilePageResponse
     */
    has_next: boolean;
}

/**
 * Check if a given object implements the DaplaDataFilePageResponse interface.
 */
export function instanceOfDaplaDataFilePageResponse(value: object): value is DaplaDataFilePageResponse {
    if (!('data_files' in value) || value['data_files'] === undefined) return false;
    if (!('total_data_files' in value) || value['total_data_files'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('page_size' in value) || value['page_size'] === undefined) return false;
    if (!('has_next' in value) || value['has_next'] === undefined) return false;
    return true;
}

export function DaplaDataFilePageResponseFromJSON(json: any): DaplaDataFilePageResponse {
    return DaplaDataFilePageResponseFromJSONTyped(json, false);
}

export function DaplaDataFilePageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DaplaDataFilePageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data_files': ((json['data_files'] as Array<any>).map(DaplaDataFileDTOFromJSON)),
        'total_data_files': json['total_data_files'],
        'page': json['page'],
        'page_size': json['page_size'],
        'has_next': json['has_next'],
    };
}

export function DaplaDataFilePageResponseToJSON(json: any): DaplaDataFilePageResponse {
    return DaplaDataFilePageResponseToJSONTyped(json, false);
}

export function DaplaDataFilePageResponseToJSONTyped(value?: DaplaDataFilePageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_files': ((value['data_files'] as Array<any>).map(DaplaDataFileDTOToJSON)),
        'total_data_files': value['total_data_files'],
        'page': value['page'],
        'page_size': value['page_size'],
        'has_next': value['has_next'],
    };
}

