/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetDTO } from './DatasetDTO';
import {
    DatasetDTOFromJSON,
    DatasetDTOFromJSONTyped,
    DatasetDTOToJSON,
    DatasetDTOToJSONTyped,
} from './DatasetDTO';

/**
 * 
 * @export
 * @interface DatasetPageResponse
 */
export interface DatasetPageResponse {
    /**
     * 
     * @type {Array<DatasetDTO>}
     * @memberof DatasetPageResponse
     */
    datasets: Array<DatasetDTO>;
    /**
     * 
     * @type {number}
     * @memberof DatasetPageResponse
     */
    total_datasets: number;
    /**
     * 
     * @type {number}
     * @memberof DatasetPageResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DatasetPageResponse
     */
    page_size: number;
    /**
     * 
     * @type {boolean}
     * @memberof DatasetPageResponse
     */
    has_next: boolean;
}

/**
 * Check if a given object implements the DatasetPageResponse interface.
 */
export function instanceOfDatasetPageResponse(value: object): value is DatasetPageResponse {
    if (!('datasets' in value) || value['datasets'] === undefined) return false;
    if (!('total_datasets' in value) || value['total_datasets'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('page_size' in value) || value['page_size'] === undefined) return false;
    if (!('has_next' in value) || value['has_next'] === undefined) return false;
    return true;
}

export function DatasetPageResponseFromJSON(json: any): DatasetPageResponse {
    return DatasetPageResponseFromJSONTyped(json, false);
}

export function DatasetPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'datasets': ((json['datasets'] as Array<any>).map(DatasetDTOFromJSON)),
        'total_datasets': json['total_datasets'],
        'page': json['page'],
        'page_size': json['page_size'],
        'has_next': json['has_next'],
    };
}

export function DatasetPageResponseToJSON(json: any): DatasetPageResponse {
    return DatasetPageResponseToJSONTyped(json, false);
}

export function DatasetPageResponseToJSONTyped(value?: DatasetPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datasets': ((value['datasets'] as Array<any>).map(DatasetDTOToJSON)),
        'total_datasets': value['total_datasets'],
        'page': value['page'],
        'page_size': value['page_size'],
        'has_next': value['has_next'],
    };
}

