/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of data product.
 * @export
 */
export const DataProductType = {
    /**
    * An other data product is a collection of related data files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product.
    */
    OTHER_DATA_PRODUCT: 'OTHER_DATA_PRODUCT',
    /**
    * A statistic product is a collection of related data files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register.
    */
    STATISTIC_PRODUCT: 'STATISTIC_PRODUCT'
} as const;
export type DataProductType = typeof DataProductType[keyof typeof DataProductType];


export function instanceOfDataProductType(value: any): boolean {
    for (const key in DataProductType) {
        if (Object.prototype.hasOwnProperty.call(DataProductType, key)) {
            if (DataProductType[key as keyof typeof DataProductType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataProductTypeFromJSON(json: any): DataProductType {
    return DataProductTypeFromJSONTyped(json, false);
}

export function DataProductTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataProductType {
    return json as DataProductType;
}

export function DataProductTypeToJSON(value?: DataProductType | null): any {
    return value as any;
}

export function DataProductTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DataProductType {
    return value as DataProductType;
}

