/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Assessment } from './Assessment';
import {
    AssessmentFromJSON,
    AssessmentFromJSONTyped,
    AssessmentToJSON,
    AssessmentToJSONTyped,
} from './Assessment';
import type { DatasetState } from './DatasetState';
import {
    DatasetStateFromJSON,
    DatasetStateFromJSONTyped,
    DatasetStateToJSON,
    DatasetStateToJSONTyped,
} from './DatasetState';

/**
 * A Dataset is a group of data files within one product and state with the same short description.
 * @export
 * @interface DatasetDTO
 */
export interface DatasetDTO {
    /**
     * 
     * @type {string}
     * @memberof DatasetDTO
     */
    id?: string | null;
    /**
     * The name of the storage location where the dataset is stored. In the case of object storage, this is the name of the bucket.
     * @type {string}
     * @memberof DatasetDTO
     */
    storage_location_name?: string | null;
    /**
     * The identifier of the product this dataset belongs to, sourced from the file path.
     * @type {string}
     * @memberof DatasetDTO
     */
    product_short_name?: string | null;
    /**
     * A short description of the dataset, sourced from the file path. \[Defined in the Dapla Manual.\](https://manual.dapla.ssb.no/statistikkere/navnestandard.html#filnavn)
     * @type {string}
     * @memberof DatasetDTO
     */
    short_description?: string | null;
    /**
     * 
     * @type {Assessment}
     * @memberof DatasetDTO
     */
    assessment?: Assessment | null;
    /**
     * 
     * @type {DatasetState}
     * @memberof DatasetDTO
     */
    dataset_state?: DatasetState | null;
    /**
     * The uniform name of the Dapla team which owns the dataset.
     * @type {string}
     * @memberof DatasetDTO
     */
    owner?: string | null;
}



/**
 * Check if a given object implements the DatasetDTO interface.
 */
export function instanceOfDatasetDTO(value: object): value is DatasetDTO {
    return true;
}

export function DatasetDTOFromJSON(json: any): DatasetDTO {
    return DatasetDTOFromJSONTyped(json, false);
}

export function DatasetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'storage_location_name': json['storage_location_name'] == null ? undefined : json['storage_location_name'],
        'product_short_name': json['product_short_name'] == null ? undefined : json['product_short_name'],
        'short_description': json['short_description'] == null ? undefined : json['short_description'],
        'assessment': json['assessment'] == null ? undefined : AssessmentFromJSON(json['assessment']),
        'dataset_state': json['dataset_state'] == null ? undefined : DatasetStateFromJSON(json['dataset_state']),
        'owner': json['owner'] == null ? undefined : json['owner'],
    };
}

export function DatasetDTOToJSON(json: any): DatasetDTO {
    return DatasetDTOToJSONTyped(json, false);
}

export function DatasetDTOToJSONTyped(value?: DatasetDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'storage_location_name': value['storage_location_name'],
        'product_short_name': value['product_short_name'],
        'short_description': value['short_description'],
        'assessment': AssessmentToJSON(value['assessment']),
        'dataset_state': DatasetStateToJSON(value['dataset_state']),
        'owner': value['owner'],
    };
}

