/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileType = {
    PARQUET: 'PARQUET',
    PARQUET_PARTITIONED: 'PARQUET_PARTITIONED',
    CSV: 'CSV',
    JSON: 'JSON',
    XML: 'XML',
    XLSX: 'XLSX'
} as const;
export type FileType = typeof FileType[keyof typeof FileType];


export function instanceOfFileType(value: any): boolean {
    for (const key in FileType) {
        if (Object.prototype.hasOwnProperty.call(FileType, key)) {
            if (FileType[key as keyof typeof FileType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileTypeFromJSON(json: any): FileType {
    return FileTypeFromJSONTyped(json, false);
}

export function FileTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileType {
    return json as FileType;
}

export function FileTypeToJSON(value?: FileType | null): any {
    return value as any;
}

export function FileTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FileType {
    return value as FileType;
}

