/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NamingViolationSummaryResponse
 */
export interface NamingViolationSummaryResponse {
    /**
     * 
     * @type {string}
     * @memberof NamingViolationSummaryResponse
     */
    reported_at: string;
    /**
     * 
     * @type {number}
     * @memberof NamingViolationSummaryResponse
     */
    number_of_violations: number;
}

/**
 * Check if a given object implements the NamingViolationSummaryResponse interface.
 */
export function instanceOfNamingViolationSummaryResponse(value: object): value is NamingViolationSummaryResponse {
    if (!('reported_at' in value) || value['reported_at'] === undefined) return false;
    if (!('number_of_violations' in value) || value['number_of_violations'] === undefined) return false;
    return true;
}

export function NamingViolationSummaryResponseFromJSON(json: any): NamingViolationSummaryResponse {
    return NamingViolationSummaryResponseFromJSONTyped(json, false);
}

export function NamingViolationSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamingViolationSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reported_at': json['reported_at'],
        'number_of_violations': json['number_of_violations'],
    };
}

export function NamingViolationSummaryResponseToJSON(json: any): NamingViolationSummaryResponse {
    return NamingViolationSummaryResponseToJSONTyped(json, false);
}

export function NamingViolationSummaryResponseToJSONTyped(value?: NamingViolationSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reported_at': value['reported_at'],
        'number_of_violations': value['number_of_violations'],
    };
}

