/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NamingViolationResponse } from './NamingViolationResponse';
import {
    instanceOfNamingViolationResponse,
    NamingViolationResponseFromJSON,
    NamingViolationResponseFromJSONTyped,
    NamingViolationResponseToJSON,
} from './NamingViolationResponse';
import type { NamingViolationSummaryResponse } from './NamingViolationSummaryResponse';
import {
    instanceOfNamingViolationSummaryResponse,
    NamingViolationSummaryResponseFromJSON,
    NamingViolationSummaryResponseFromJSONTyped,
    NamingViolationSummaryResponseToJSON,
} from './NamingViolationSummaryResponse';

/**
 * @type NamingViolations200Response
 * 
 * @export
 */
export type NamingViolations200Response = NamingViolationResponse | NamingViolationSummaryResponse;

export function NamingViolations200ResponseFromJSON(json: any): NamingViolations200Response {
    return NamingViolations200ResponseFromJSONTyped(json, false);
}

export function NamingViolations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamingViolations200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfNamingViolationResponse(json)) {
        return NamingViolationResponseFromJSONTyped(json, true);
    }
    if (instanceOfNamingViolationSummaryResponse(json)) {
        return NamingViolationSummaryResponseFromJSONTyped(json, true);
    }
    return {} as any;
}

export function NamingViolations200ResponseToJSON(json: any): any {
    return NamingViolations200ResponseToJSONTyped(json, false);
}

export function NamingViolations200ResponseToJSONTyped(value?: NamingViolations200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfNamingViolationResponse(value)) {
        return NamingViolationResponseToJSON(value as NamingViolationResponse);
    }
    if (instanceOfNamingViolationSummaryResponse(value)) {
        return NamingViolationSummaryResponseToJSON(value as NamingViolationSummaryResponse);
    }
    return {};
}

