/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PeriodFormat = {
    YEAR: 'YEAR',
    YEAR_MONTH: 'YEAR_MONTH',
    YEAR_MONTH_DAY: 'YEAR_MONTH_DAY',
    YEAR_WEEK: 'YEAR_WEEK',
    BIMESTER: 'BIMESTER',
    QUARTER: 'QUARTER',
    TRIANNUAL: 'TRIANNUAL',
    HALF_YEAR: 'HALF_YEAR'
} as const;
export type PeriodFormat = typeof PeriodFormat[keyof typeof PeriodFormat];


export function instanceOfPeriodFormat(value: any): boolean {
    for (const key in PeriodFormat) {
        if (Object.prototype.hasOwnProperty.call(PeriodFormat, key)) {
            if (PeriodFormat[key as keyof typeof PeriodFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PeriodFormatFromJSON(json: any): PeriodFormat {
    return PeriodFormatFromJSONTyped(json, false);
}

export function PeriodFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriodFormat {
    return json as PeriodFormat;
}

export function PeriodFormatToJSON(value?: PeriodFormat | null): any {
    return value as any;
}

export function PeriodFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): PeriodFormat {
    return value as PeriodFormat;
}

