/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskCommand } from './TaskCommand';
import {
    TaskCommandFromJSON,
    TaskCommandFromJSONTyped,
    TaskCommandToJSON,
    TaskCommandToJSONTyped,
} from './TaskCommand';

/**
 * Register a command for a task. \[jobId\] is opaque to us: we only ever compare it for equality against the job id supplied with subsequent data file writes.
 * @export
 * @interface TaskRegistration
 */
export interface TaskRegistration {
    /**
     * 
     * @type {TaskCommand}
     * @memberof TaskRegistration
     */
    command: TaskCommand;
    /**
     * 
     * @type {string}
     * @memberof TaskRegistration
     */
    job_id: string;
}



/**
 * Check if a given object implements the TaskRegistration interface.
 */
export function instanceOfTaskRegistration(value: object): value is TaskRegistration {
    if (!('command' in value) || value['command'] === undefined) return false;
    if (!('job_id' in value) || value['job_id'] === undefined) return false;
    return true;
}

export function TaskRegistrationFromJSON(json: any): TaskRegistration {
    return TaskRegistrationFromJSONTyped(json, false);
}

export function TaskRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'command': TaskCommandFromJSON(json['command']),
        'job_id': json['job_id'],
    };
}

export function TaskRegistrationToJSON(json: any): TaskRegistration {
    return TaskRegistrationToJSONTyped(json, false);
}

export function TaskRegistrationToJSONTyped(value?: TaskRegistration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': TaskCommandToJSON(value['command']),
        'job_id': value['job_id'],
    };
}

