/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TaskCommand = {
    /**
    * The job is now the only one permitted to write data files for the task.
    */
    START: 'start',
    /**
    * The job has finished reporting data files for the task. Every file the task had claimed which this job did not report is deleted, along with any dataset and data product left empty. Only send this after an exhaustive, successful listing of the source: an incomplete listing is indistinguishable from data having been removed, and will be acted on as such. The job stays active afterwards. Completing prunes metadata, it does not close the task.
    */
    COMPLETE: 'complete',
    /**
    * The job has failed before reporting all data files.
    */
    PARTIAL: 'partial',
    /**
    * The job has aborted before reporting any data files.
    */
    ABORTED: 'aborted'
} as const;
export type TaskCommand = typeof TaskCommand[keyof typeof TaskCommand];


export function instanceOfTaskCommand(value: any): boolean {
    for (const key in TaskCommand) {
        if (Object.prototype.hasOwnProperty.call(TaskCommand, key)) {
            if (TaskCommand[key as keyof typeof TaskCommand] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TaskCommandFromJSON(json: any): TaskCommand {
    return TaskCommandFromJSONTyped(json, false);
}

export function TaskCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCommand {
    return json as TaskCommand;
}

export function TaskCommandToJSON(value?: TaskCommand | null): any {
    return value as any;
}

export function TaskCommandToJSONTyped(value: any, ignoreDiscriminator: boolean): TaskCommand {
    return value as TaskCommand;
}

