/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDaplaDataFile,
  DaplaDataFileDTO,
  Problem,
} from '../models/index';
import {
    CreateDaplaDataFileFromJSON,
    CreateDaplaDataFileToJSON,
    DaplaDataFileDTOFromJSON,
    DaplaDataFileDTOToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface CreateOrUpdateDaplaDataFileRequest {
    createDaplaDataFile: CreateDaplaDataFile;
}

export interface GetDataFileByFilePathRequest {
    filePath: string;
}

export interface ListDataFilesRequest {
    datasetId?: string | null;
}

/**
 * DataFilesApi - interface
 * 
 * @export
 * @interface DataFilesApiInterface
 */
export interface DataFilesApiInterface {
    /**
     * 
     * @param {CreateDaplaDataFile} createDaplaDataFile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataFilesApiInterface
     */
    createOrUpdateDaplaDataFileRaw(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    createOrUpdateDaplaDataFile(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} filePath 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataFilesApiInterface
     */
    getDataFileByFilePathRaw(requestParameters: GetDataFileByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaplaDataFileDTO>>;

    /**
     */
    getDataFileByFilePath(requestParameters: GetDataFileByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaplaDataFileDTO>;

    /**
     * 
     * @param {string} [datasetId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataFilesApiInterface
     */
    listDataFilesRaw(requestParameters: ListDataFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DaplaDataFileDTO>>>;

    /**
     */
    listDataFiles(requestParameters: ListDataFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DaplaDataFileDTO>>;

}

/**
 * 
 */
export class DataFilesApi extends runtime.BaseAPI implements DataFilesApiInterface {

    /**
     */
    async createOrUpdateDaplaDataFileRaw(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createDaplaDataFile'] == null) {
            throw new runtime.RequiredError(
                'createDaplaDataFile',
                'Required parameter "createDaplaDataFile" was null or undefined when calling createOrUpdateDaplaDataFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("metamapper-datadoc-m2m", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data-files`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDaplaDataFileToJSON(requestParameters['createDaplaDataFile']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createOrUpdateDaplaDataFile(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createOrUpdateDaplaDataFileRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getDataFileByFilePathRaw(requestParameters: GetDataFileByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaplaDataFileDTO>> {
        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling getDataFileByFilePath().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("keycloak-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data-files/{file-path}`;
        urlPath = urlPath.replace(`{${"file-path"}}`, encodeURIComponent(String(requestParameters['filePath'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaplaDataFileDTOFromJSON(jsonValue));
    }

    /**
     */
    async getDataFileByFilePath(requestParameters: GetDataFileByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaplaDataFileDTO> {
        const response = await this.getDataFileByFilePathRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDataFilesRaw(requestParameters: ListDataFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DaplaDataFileDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['datasetId'] != null) {
            queryParameters['dataset_id'] = requestParameters['datasetId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("keycloak-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data-files`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DaplaDataFileDTOFromJSON));
    }

    /**
     */
    async listDataFiles(requestParameters: ListDataFilesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DaplaDataFileDTO>> {
        const response = await this.listDataFilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
