/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DataProductDTO,
  DataProductType,
  Problem,
} from '../models/index';
import {
    DataProductDTOFromJSON,
    DataProductDTOToJSON,
    DataProductTypeFromJSON,
    DataProductTypeToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface GetDataProductByShortNameRequest {
    shortName: string;
}

export interface ListDataProductsRequest {
    productType?: DataProductType | null;
}

/**
 * DataProductsApi - interface
 * 
 * @export
 * @interface DataProductsApiInterface
 */
export interface DataProductsApiInterface {
    /**
     * 
     * @param {string} shortName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataProductsApiInterface
     */
    getDataProductByShortNameRaw(requestParameters: GetDataProductByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataProductDTO>>;

    /**
     */
    getDataProductByShortName(requestParameters: GetDataProductByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataProductDTO>;

    /**
     * 
     * @param {DataProductType} [productType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataProductsApiInterface
     */
    listDataProductsRaw(requestParameters: ListDataProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataProductDTO>>>;

    /**
     */
    listDataProducts(requestParameters: ListDataProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataProductDTO>>;

}

/**
 * 
 */
export class DataProductsApi extends runtime.BaseAPI implements DataProductsApiInterface {

    /**
     */
    async getDataProductByShortNameRaw(requestParameters: GetDataProductByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataProductDTO>> {
        if (requestParameters['shortName'] == null) {
            throw new runtime.RequiredError(
                'shortName',
                'Required parameter "shortName" was null or undefined when calling getDataProductByShortName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("keycloak-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data-products/{short-name}`;
        urlPath = urlPath.replace(`{${"short-name"}}`, encodeURIComponent(String(requestParameters['shortName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataProductDTOFromJSON(jsonValue));
    }

    /**
     */
    async getDataProductByShortName(requestParameters: GetDataProductByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataProductDTO> {
        const response = await this.getDataProductByShortNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDataProductsRaw(requestParameters: ListDataProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataProductDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['productType'] != null) {
            queryParameters['productType'] = requestParameters['productType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("keycloak-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data-products`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataProductDTOFromJSON));
    }

    /**
     */
    async listDataProducts(requestParameters: ListDataProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataProductDTO>> {
        const response = await this.listDataProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
