/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DatasetDTO,
  Problem,
} from '../models/index';
import {
    DatasetDTOFromJSON,
    DatasetDTOToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface DeleteDatasetByIdRequest {
    id: string;
}

export interface GetDatasetByIdRequest {
    id: string;
}

export interface ListDatasetsRequest {
    productShortName?: string | null;
}

/**
 * DatasetsApi - interface
 * 
 * @export
 * @interface DatasetsApiInterface
 */
export interface DatasetsApiInterface {
    /**
     * Delete a dataset. Also deletes the data files which make up this dataset. May delete a data product if this is the only dataset which is part of the product.
     * @summary Delete a dataset.
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatasetsApiInterface
     */
    deleteDatasetByIdRaw(requestParameters: DeleteDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a dataset. Also deletes the data files which make up this dataset. May delete a data product if this is the only dataset which is part of the product.
     * Delete a dataset.
     */
    deleteDatasetById(requestParameters: DeleteDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatasetsApiInterface
     */
    getDatasetByIdRaw(requestParameters: GetDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatasetDTO>>;

    /**
     */
    getDatasetById(requestParameters: GetDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatasetDTO>;

    /**
     * 
     * @param {string} [productShortName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatasetsApiInterface
     */
    listDatasetsRaw(requestParameters: ListDatasetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DatasetDTO>>>;

    /**
     */
    listDatasets(requestParameters: ListDatasetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DatasetDTO>>;

}

/**
 * 
 */
export class DatasetsApi extends runtime.BaseAPI implements DatasetsApiInterface {

    /**
     * Delete a dataset. Also deletes the data files which make up this dataset. May delete a data product if this is the only dataset which is part of the product.
     * Delete a dataset.
     */
    async deleteDatasetByIdRaw(requestParameters: DeleteDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDatasetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("keycloak-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datasets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a dataset. Also deletes the data files which make up this dataset. May delete a data product if this is the only dataset which is part of the product.
     * Delete a dataset.
     */
    async deleteDatasetById(requestParameters: DeleteDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDatasetByIdRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getDatasetByIdRaw(requestParameters: GetDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatasetDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDatasetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("keycloak-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datasets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatasetDTOFromJSON(jsonValue));
    }

    /**
     */
    async getDatasetById(requestParameters: GetDatasetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatasetDTO> {
        const response = await this.getDatasetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDatasetsRaw(requestParameters: ListDatasetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DatasetDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['productShortName'] != null) {
            queryParameters['product_short_name'] = requestParameters['productShortName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("keycloak-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datasets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DatasetDTOFromJSON));
    }

    /**
     */
    async listDatasets(requestParameters: ListDatasetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DatasetDTO>> {
        const response = await this.listDatasetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
