/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDaplaDataFile,
  DaplaDataFileDTO,
  DataProductDTO,
  DataProductType,
  DatasetDTO,
  Problem,
} from '../models/index';
import {
    CreateDaplaDataFileFromJSON,
    CreateDaplaDataFileToJSON,
    DaplaDataFileDTOFromJSON,
    DaplaDataFileDTOToJSON,
    DataProductDTOFromJSON,
    DataProductDTOToJSON,
    DataProductTypeFromJSON,
    DataProductTypeToJSON,
    DatasetDTOFromJSON,
    DatasetDTOToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface CreateOrUpdateDaplaDataFileRequest {
    createDaplaDataFile: CreateDaplaDataFile;
}

export interface GetByFilePathRequest {
    filePath: string;
}

export interface GetByIdRequest {
    id: string;
}

export interface GetByShortNameRequest {
    shortName: string;
}

export interface ListDaplaDataFilesRequest {
    datasetId?: string | null;
}

export interface ListDataProductsRequest {
    productType?: DataProductType | null;
}

export interface ListDatasetsRequest {
    productShortName?: string | null;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @param {CreateDaplaDataFile} createDaplaDataFile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createOrUpdateDaplaDataFileRaw(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    createOrUpdateDaplaDataFile(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} filePath 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getByFilePathRaw(requestParameters: GetByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaplaDataFileDTO>>;

    /**
     */
    getByFilePath(requestParameters: GetByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaplaDataFileDTO>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getByIdRaw(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatasetDTO>>;

    /**
     */
    getById(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatasetDTO>;

    /**
     * 
     * @param {string} shortName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getByShortNameRaw(requestParameters: GetByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataProductDTO>>;

    /**
     */
    getByShortName(requestParameters: GetByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataProductDTO>;

    /**
     * 
     * @param {string} [datasetId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listDaplaDataFilesRaw(requestParameters: ListDaplaDataFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    listDaplaDataFiles(requestParameters: ListDaplaDataFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {DataProductType} [productType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listDataProductsRaw(requestParameters: ListDataProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataProductDTO>>>;

    /**
     */
    listDataProducts(requestParameters: ListDataProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataProductDTO>>;

    /**
     * 
     * @param {string} [productShortName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listDatasetsRaw(requestParameters: ListDatasetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DatasetDTO>>>;

    /**
     */
    listDatasets(requestParameters: ListDatasetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DatasetDTO>>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     */
    async createOrUpdateDaplaDataFileRaw(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createDaplaDataFile'] == null) {
            throw new runtime.RequiredError(
                'createDaplaDataFile',
                'Required parameter "createDaplaDataFile" was null or undefined when calling createOrUpdateDaplaDataFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/data-files`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDaplaDataFileToJSON(requestParameters['createDaplaDataFile']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createOrUpdateDaplaDataFile(requestParameters: CreateOrUpdateDaplaDataFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createOrUpdateDaplaDataFileRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getByFilePathRaw(requestParameters: GetByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaplaDataFileDTO>> {
        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling getByFilePath().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/data-files/{filePath}`;
        urlPath = urlPath.replace(`{${"filePath"}}`, encodeURIComponent(String(requestParameters['filePath'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaplaDataFileDTOFromJSON(jsonValue));
    }

    /**
     */
    async getByFilePath(requestParameters: GetByFilePathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaplaDataFileDTO> {
        const response = await this.getByFilePathRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getByIdRaw(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatasetDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/datasets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatasetDTOFromJSON(jsonValue));
    }

    /**
     */
    async getById(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatasetDTO> {
        const response = await this.getByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getByShortNameRaw(requestParameters: GetByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataProductDTO>> {
        if (requestParameters['shortName'] == null) {
            throw new runtime.RequiredError(
                'shortName',
                'Required parameter "shortName" was null or undefined when calling getByShortName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/data-products/{short_name}`;
        urlPath = urlPath.replace(`{${"short_name"}}`, encodeURIComponent(String(requestParameters['shortName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataProductDTOFromJSON(jsonValue));
    }

    /**
     */
    async getByShortName(requestParameters: GetByShortNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataProductDTO> {
        const response = await this.getByShortNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDaplaDataFilesRaw(requestParameters: ListDaplaDataFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['datasetId'] != null) {
            queryParameters['dataset-id'] = requestParameters['datasetId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/data-files`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async listDaplaDataFiles(requestParameters: ListDaplaDataFilesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listDaplaDataFilesRaw(requestParameters, initOverrides);
    }

    /**
     */
    async listDataProductsRaw(requestParameters: ListDataProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataProductDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['productType'] != null) {
            queryParameters['product_type'] = requestParameters['productType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/data-products`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataProductDTOFromJSON));
    }

    /**
     */
    async listDataProducts(requestParameters: ListDataProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataProductDTO>> {
        const response = await this.listDataProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDatasetsRaw(requestParameters: ListDatasetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DatasetDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['productShortName'] != null) {
            queryParameters['product_short_name'] = requestParameters['productShortName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/datasets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DatasetDTOFromJSON));
    }

    /**
     */
    async listDatasets(requestParameters: ListDatasetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DatasetDTO>> {
        const response = await this.listDatasetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
