/* tslint:disable */
/* eslint-disable */
/**
 * Internal Datadoc API
 * Service to maintain and expose metadata for data in Statistics Norway. Includes the following concepts:  - Data File: A logically defined blob of data from a file system or object storage. - Dataset: A collection of related Data Files which together represent a coherent dataset. These are typically partitioned by time periods. - Data Product: A collection of related Data Files that are produced and maintained by a Dapla team. All data which does not directly contribute to publication of a statistic on ssb.no is defined as a Data Product. - Statistic Product: A collection of related Data Files that are produced and maintained by a Dapla team, and directly contribute to publication of a statistic on ssb.no. The list of all statistic products is defined by the Statistic Register. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: metadata@ssb.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Problem,
  TaskRegistration,
} from '../models/index';
import {
    ProblemFromJSON,
    ProblemToJSON,
    TaskRegistrationFromJSON,
    TaskRegistrationToJSON,
} from '../models/index';

export interface RegisterTaskRequest {
    taskId: string;
    taskRegistration: TaskRegistration;
}

/**
 * TaskRegistrationApi - interface
 * 
 * @export
 * @interface TaskRegistrationApiInterface
 */
export interface TaskRegistrationApiInterface {
    /**
     * 
     * @param {string} taskId 
     * @param {TaskRegistration} taskRegistration 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskRegistrationApiInterface
     */
    registerTaskRaw(requestParameters: RegisterTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    registerTask(requestParameters: RegisterTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class TaskRegistrationApi extends runtime.BaseAPI implements TaskRegistrationApiInterface {

    /**
     */
    async registerTaskRaw(requestParameters: RegisterTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling registerTask().'
            );
        }

        if (requestParameters['taskRegistration'] == null) {
            throw new runtime.RequiredError(
                'taskRegistration',
                'Required parameter "taskRegistration" was null or undefined when calling registerTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("metamapper-datadoc-m2m", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tasks/{task-id}`;
        urlPath = urlPath.replace(`{${"task-id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskRegistrationToJSON(requestParameters['taskRegistration']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async registerTask(requestParameters: RegisterTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.registerTaskRaw(requestParameters, initOverrides);
    }

}
