name: Image Build and Deploy

on:
  release:
    types: [published]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cluster:
        description: "Which cluster to deploy to?"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod

jobs:
  docker-build:
    name: Docker build
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
      actions: "read"
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
      prod-config-changed: ${{ steps.prod-config-changed.outputs.changed != 'non-inputs' }}
      test-config-changed: ${{ steps.test-config-changed.outputs.changed != 'non-inputs' }}
      only-config-changed: ${{ steps.changed-files.outputs.changed == 'only-inputs'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check what changed
        id: changed-files
        uses: "nais/what-changed@main"
        with:
          files: .nais/**/nais.yaml
      - name: Check for test config changes
        id: test-config-changed
        uses: "nais/what-changed@main"
        with:
          files: .nais/test/nais.yaml
      - name: Check for prod config changes
        id: prod-config-changed
        uses: "nais/what-changed@main"
        with:
          files: .nais/prod/nais.yaml

      - name: Build and push
        if: steps.changed-files.outputs.changed != 'only-inputs' || github.event.inputs.cluster == 'test' || github.event.inputs.cluster == 'prod'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dapla-metadata

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-test:
    name: Deploy to test
    needs: docker-build
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    runs-on: ubuntu-latest
    if: github.event_name != 'release' || github.event.inputs.cluster == 'test' || needs.docker-build.outputs.test-config-changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: test
          RESOURCE: .nais/test/nais.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
          WORKLOAD_IMAGE: ${{ needs.docker-build.outputs.image }}
          TELEMETRY: ${{ needs.docker-build.outputs.telemetry }}

  deploy-prod:
    name: Deploy to prod
    needs: docker-build
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event.inputs.cluster == 'prod' || (needs.docker-build.outputs.prod-config-changed == 'true' && needs.docker-build.outputs.only-config-changed == 'true')
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod
          RESOURCE: .nais/prod/nais.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
          WORKLOAD_IMAGE: ${{ needs.docker-build.outputs.image }}
          TELEMETRY: ${{ needs.docker-build.outputs.telemetry }}
