name: Dependency scan

on:
  push:
    branches:
      - chore/remove-dependency-scan
  workflow_dispatch:

jobs:
  grype-scan:
    uses: statisticsnorway/metadata-system/.github/workflows/dependency-scan.yaml@v1
    permissions:
      contents: read
      security-events: write
      packages: read
      actions: read
    with:
      docker-context: .
      dockerfile: Dockerfile
      image: docker build . --file Dockerfile --tag ssb-dataportal:latest